import test from 'node:test';
import assert from 'node:assert/strict';

import type { Exercise } from '../src/generator/types';
import { parseDbArg, serializeGeneratedFile } from '../scripts/generate-exercises';

test('parseDbArg returns all three dbs by default', () => {
  assert.deepEqual(parseDbArg([]), ['aperture', 'sideline', 'rove']);
});

test('parseDbArg returns a single db when --db is given', () => {
  assert.deepEqual(parseDbArg(['--db', 'rove']), ['rove']);
});

test('parseDbArg rejects an unknown db', () => {
  assert.throws(() => parseDbArg(['--db', 'nope']), /unknown --db/);
});

test('serializeGeneratedFile emits a sorted, typed GENERATED_EXERCISES map', () => {
  const ex = {
    id: 'z1',
    skill: 'ap-order-by',
    database: 'aperture',
    task: 't',
    starterSql: { full: '', half: '', blank: '' },
    blankMap: { full: {}, half: {}, blank: {} },
    hint: 'h',
    expectedSql: 'SELECT 1 AS one',
    orderMatters: true,
    rowCeiling: 200,
    fingerprint: { columns: ['one'], rowCount: 1, orderedRowHash: 'a', unorderedRowHash: 'b' }
  } as Exercise;
  const out = serializeGeneratedFile({ 'ap-order-by': [ex] });
  assert.match(out, /AUTO-GENERATED by scripts\/generate-exercises\.ts/);
  assert.match(out, /import type \{ Exercise \} from '\.\.\/\.\.\/generator\/types';/);
  assert.match(out, /export const GENERATED_EXERCISES: Record<string, Exercise\[\]> =/);
  assert.match(out, /"ap-order-by"/);
  assert.match(out, /"orderedRowHash": "a"/);
});
