// AUTO-GENERATED by scripts/generate-exercises.ts. DO NOT EDIT BY HAND.
// Regenerate with: npm run generate-exercises
import type { Exercise } from '../../generator/types';

export const GENERATED_EXERCISES: Record<string, Exercise[]> = {
  "sl-anti-join": [
    {
      "id": "sl-anti-join-5w5sqp",
      "skill": "sl-anti-join",
      "database": "sideline",
      "task": "Which sponsors have zero team deals? Return sponsor_id, sponsor_name using an anti-join, ordered by sponsor_id. Return columns: sponsor_id, sponsor_name. Order by: sponsor_id.",
      "starterSql": {
        "full": "SELECT s.sponsor_id AS sponsor_id, s.name AS sponsor_name FROM sponsor s LEFT JOIN team_sponsor ts ON ts.sponsor_id = s.sponsor_id WHERE ts.sponsor_id IS NULL ORDER BY __BLANK_0__",
        "half": "SELECT s.sponsor_id AS sponsor_id, s.name AS sponsor_name FROM sponsor s LEFT JOIN team_sponsor ts ON ts.sponsor_id = s.sponsor_id WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "sponsor_id"
        },
        "half": {
          "__BLANK_0__": "ts.sponsor_id IS NULL",
          "__BLANK_1__": "sponsor_id"
        },
        "blank": {
          "__BLANK_0__": "s.sponsor_id AS sponsor_id, s.name AS sponsor_name",
          "__BLANK_1__": "sponsor s LEFT JOIN team_sponsor ts ON ts.sponsor_id = s.sponsor_id",
          "__BLANK_2__": "ts.sponsor_id IS NULL",
          "__BLANK_3__": "sponsor_id"
        }
      },
      "hint": "LEFT JOIN team_sponsor on sponsor_id and keep NULL matches. The manifest reserves sponsor 30 as team-less.",
      "expectedSql": "SELECT s.sponsor_id AS sponsor_id, s.name AS sponsor_name FROM sponsor s LEFT JOIN team_sponsor ts ON ts.sponsor_id = s.sponsor_id WHERE ts.sponsor_id IS NULL ORDER BY sponsor_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "sponsor_id",
          "sponsor_name"
        ],
        "rowCount": 1,
        "orderedRowHash": "991a4e443892021c66414f0a775037e6aaf9a991b3257c1910a39c727a310195",
        "unorderedRowHash": "991a4e443892021c66414f0a775037e6aaf9a991b3257c1910a39c727a310195"
      }
    },
    {
      "id": "sl-anti-join-bfhzmq",
      "skill": "sl-anti-join",
      "database": "sideline",
      "task": "Which teams have zero matches? Return team_id, team_name using an anti-join, ordered by team_id. Return columns: team_id, team_name. Order by: team_id.",
      "starterSql": {
        "full": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t LEFT JOIN match m ON (m.team_a_id = t.team_id OR m.team_b_id = t.team_id) WHERE m.match_id IS NULL ORDER BY __BLANK_0__",
        "half": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t LEFT JOIN match m ON (m.team_a_id = t.team_id OR m.team_b_id = t.team_id) WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id"
        },
        "half": {
          "__BLANK_0__": "m.match_id IS NULL",
          "__BLANK_1__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "t.team_id AS team_id, t.name AS team_name",
          "__BLANK_1__": "team t LEFT JOIN match m ON (m.team_a_id = t.team_id OR m.team_b_id = t.team_id)",
          "__BLANK_2__": "m.match_id IS NULL",
          "__BLANK_3__": "team_id"
        }
      },
      "hint": "LEFT JOIN match on either team column, then keep only rows where the match side is NULL. The manifest guarantees team 40 never played.",
      "expectedSql": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t LEFT JOIN match m ON (m.team_a_id = t.team_id OR m.team_b_id = t.team_id) WHERE m.match_id IS NULL ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name"
        ],
        "rowCount": 1,
        "orderedRowHash": "71d71cc9e2a3392f39c92385f0795f1c07fff10607f27dc495531da2b3de4d63",
        "unorderedRowHash": "71d71cc9e2a3392f39c92385f0795f1c07fff10607f27dc495531da2b3de4d63"
      }
    },
    {
      "id": "sl-anti-join-bfhzmq",
      "skill": "sl-anti-join",
      "database": "sideline",
      "task": "Find sponsorless teams by anti-joining team to team_sponsor; return team_id, team_name ordered by team_id. Return columns: team_id, team_name. Order by: team_id.",
      "starterSql": {
        "full": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t LEFT JOIN team_sponsor ts ON ts.team_id = t.team_id WHERE ts.team_id IS NULL ORDER BY __BLANK_0__",
        "half": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t LEFT JOIN team_sponsor ts ON ts.team_id = t.team_id WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id"
        },
        "half": {
          "__BLANK_0__": "ts.team_id IS NULL",
          "__BLANK_1__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "t.team_id AS team_id, t.name AS team_name",
          "__BLANK_1__": "team t LEFT JOIN team_sponsor ts ON ts.team_id = t.team_id",
          "__BLANK_2__": "ts.team_id IS NULL",
          "__BLANK_3__": "team_id"
        }
      },
      "hint": "LEFT JOIN team_sponsor and keep rows where ts.team_id IS NULL. The seed guarantees sponsorless teams.",
      "expectedSql": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t LEFT JOIN team_sponsor ts ON ts.team_id = t.team_id WHERE ts.team_id IS NULL ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name"
        ],
        "rowCount": 7,
        "orderedRowHash": "f00edfa83d282aec70f53c22af5cb73f16e456778fef90bc77764a3ac2720ffd",
        "unorderedRowHash": "263e633be8f16fc9c8295ffd7ea34bf5ff7c6eba3cae0f92d7be4dc5666497c4"
      }
    },
    {
      "id": "sl-anti-join-bfhzmq",
      "skill": "sl-anti-join",
      "database": "sideline",
      "task": "Find player-less teams via NOT EXISTS against player; return team_id, team_name ordered by team_id. Return columns: team_id, team_name. Order by: team_id.",
      "starterSql": {
        "full": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t WHERE NOT EXISTS (SELECT 1 FROM player p WHERE p.team_id = t.team_id) ORDER BY __BLANK_0__",
        "half": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id"
        },
        "half": {
          "__BLANK_0__": "NOT EXISTS (SELECT 1 FROM player p WHERE p.team_id = t.team_id)",
          "__BLANK_1__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "t.team_id AS team_id, t.name AS team_name",
          "__BLANK_1__": "team t",
          "__BLANK_2__": "NOT EXISTS (SELECT 1 FROM player p WHERE p.team_id = t.team_id)",
          "__BLANK_3__": "team_id"
        }
      },
      "hint": "Use NOT EXISTS against player.team_id. The manifest guarantees team 40 has no players.",
      "expectedSql": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t WHERE NOT EXISTS (SELECT 1 FROM player p WHERE p.team_id = t.team_id) ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name"
        ],
        "rowCount": 1,
        "orderedRowHash": "71d71cc9e2a3392f39c92385f0795f1c07fff10607f27dc495531da2b3de4d63",
        "unorderedRowHash": "71d71cc9e2a3392f39c92385f0795f1c07fff10607f27dc495531da2b3de4d63"
      }
    }
  ],
  "sl-case-expression": [
    {
      "id": "sl-case-expression-1k89ftc",
      "skill": "sl-case-expression",
      "database": "sideline",
      "task": "Use CASE to bucket elo_rating into tier for every team and return team_id, team_name, tier, ordered by team_id. Return columns: team_id, team_name, tier. Order by: team_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS team_id, name AS team_name, CASE WHEN elo_rating >= 1800 THEN 'elite' WHEN elo_rating >= 1500 THEN 'mid' ELSE 'developing' END AS tier FROM team ORDER BY __BLANK_1__",
        "half": "SELECT team_id AS team_id, name AS team_name, CASE WHEN elo_rating >= 1800 THEN 'elite' WHEN elo_rating >= 1500 THEN 'mid' ELSE 'developing' END AS tier FROM team ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id",
          "__BLANK_1__": "team_id"
        },
        "half": {
          "__BLANK_0__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "team_id AS team_id, name AS team_name, CASE WHEN elo_rating >= 1800 THEN 'elite' WHEN elo_rating >= 1500 THEN 'mid' ELSE 'developing' END AS tier",
          "__BLANK_1__": "team",
          "__BLANK_2__": "team_id"
        }
      },
      "hint": "CASE WHEN ... THEN ... ELSE ... END returns the first matching branch for each row.",
      "expectedSql": "SELECT team_id AS team_id, name AS team_name, CASE WHEN elo_rating >= 1800 THEN 'elite' WHEN elo_rating >= 1500 THEN 'mid' ELSE 'developing' END AS tier FROM team ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name",
          "tier"
        ],
        "rowCount": 40,
        "orderedRowHash": "0c1f81b150e5907577209d96df3fe5b4824eead903ee460ef91f3f019b7efa91",
        "unorderedRowHash": "1919c173cc5804c0874dd9285befeca32bd79d49989526d6e4e0355f4a8a5dd1"
      }
    }
  ],
  "sl-cte": [
    {
      "id": "sl-cte-8yh97r",
      "skill": "sl-cte",
      "database": "sideline",
      "task": "Using a CTE that counts wins per team, return team_id, team_name, wins for teams with at least one win. Order by team_id. Return columns: team_id, team_name, wins. Order by: team_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS team_id, team_name AS team_name, wins AS wins FROM (WITH team_wins AS (SELECT winner_team_id AS team_id, count(*) AS wins FROM match GROUP BY winner_team_id) SELECT t.team_id AS team_id, t.name AS team_name, tw.wins AS wins FROM team t JOIN team_wins tw ON tw.team_id = t.team_id) wins_by_team ORDER BY __BLANK_1__",
        "half": "SELECT team_id AS team_id, team_name AS team_name, wins AS wins FROM (WITH team_wins AS (SELECT winner_team_id AS team_id, count(*) AS wins FROM match GROUP BY winner_team_id) SELECT t.team_id AS team_id, t.name AS team_name, tw.wins AS wins FROM team t JOIN team_wins tw ON tw.team_id = t.team_id) wins_by_team ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id",
          "__BLANK_1__": "team_id"
        },
        "half": {
          "__BLANK_0__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "team_id AS team_id, team_name AS team_name, wins AS wins",
          "__BLANK_1__": "(WITH team_wins AS (SELECT winner_team_id AS team_id, count(*) AS wins FROM match GROUP BY winner_team_id) SELECT t.team_id AS team_id, t.name AS team_name, tw.wins AS wins FROM team t JOIN team_wins tw ON tw.team_id = t.team_id) wins_by_team",
          "__BLANK_2__": "team_id"
        }
      },
      "hint": "Name the aggregate in a WITH clause, then join that named result like a table.",
      "expectedSql": "SELECT team_id AS team_id, team_name AS team_name, wins AS wins FROM (WITH team_wins AS (SELECT winner_team_id AS team_id, count(*) AS wins FROM match GROUP BY winner_team_id) SELECT t.team_id AS team_id, t.name AS team_name, tw.wins AS wins FROM team t JOIN team_wins tw ON tw.team_id = t.team_id) wins_by_team ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name",
          "wins"
        ],
        "rowCount": 34,
        "orderedRowHash": "b9840f3009124720bb8f12c4e3abc506dab4519cb2d9f9f4359adb02916ae807",
        "unorderedRowHash": "7dff2152c31ea68c88d833bcd8d8bc2d87828044863295d9c4fb0a470d81cdec"
      }
    }
  ],
  "sl-date-functions": [
    {
      "id": "sl-date-functions-m3iroe",
      "skill": "sl-date-functions",
      "database": "sideline",
      "task": "For tier S tournaments, compute length_days as end_date minus start_date. Return tournament_id, name, length_days. Order by tournament_id. Return columns: tournament_id, name, length_days. Order by: tournament_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS tournament_id, name AS name, (end_date - start_date) AS length_days FROM tournament WHERE tier = 'S' ORDER BY __BLANK_1__",
        "half": "SELECT tournament_id AS tournament_id, name AS name, (end_date - start_date) AS length_days FROM tournament WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "tournament_id",
          "__BLANK_1__": "tournament_id"
        },
        "half": {
          "__BLANK_0__": "tier = 'S'",
          "__BLANK_1__": "tournament_id"
        },
        "blank": {
          "__BLANK_0__": "tournament_id AS tournament_id, name AS name, (end_date - start_date) AS length_days",
          "__BLANK_1__": "tournament",
          "__BLANK_2__": "tier = 'S'",
          "__BLANK_3__": "tournament_id"
        }
      },
      "hint": "In Postgres, date minus date returns the integer number of days between them.",
      "expectedSql": "SELECT tournament_id AS tournament_id, name AS name, (end_date - start_date) AS length_days FROM tournament WHERE tier = 'S' ORDER BY tournament_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "tournament_id",
          "name",
          "length_days"
        ],
        "rowCount": 2,
        "orderedRowHash": "95aa86aea3e0511ea32aa21e42dc085d673a0eaf9b24c6310fdd481f4ae57d95",
        "unorderedRowHash": "c626979c2b44606dc213b46a841d00d88ece5567697972866759a29fba493b14"
      }
    }
  ],
  "sl-join-aggregate": [
    {
      "id": "sl-join-aggregate-6d5edg",
      "skill": "sl-join-aggregate",
      "database": "sideline",
      "task": "For each winning team, return team_id, team_name, match_count, and bo5_count. Order by team_id. Return columns: team_id, team_name, match_count, bo5_count. Order by: team_id.",
      "starterSql": {
        "full": "SELECT t.team_id AS team_id, t.name AS team_name, count(m.match_id) AS match_count, sum(CASE WHEN m.best_of = 5 THEN 1 ELSE 0 END) AS bo5_count FROM team t JOIN match m ON m.winner_team_id = t.team_id GROUP BY t.team_id, t.name ORDER BY __BLANK_0__",
        "half": "SELECT t.team_id AS team_id, t.name AS team_name, count(m.match_id) AS match_count, sum(CASE WHEN m.best_of = 5 THEN 1 ELSE 0 END) AS bo5_count FROM team t JOIN match m ON m.winner_team_id = t.team_id GROUP BY __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ GROUP BY __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id"
        },
        "half": {
          "__BLANK_0__": "t.team_id, t.name",
          "__BLANK_1__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "t.team_id AS team_id, t.name AS team_name, count(m.match_id) AS match_count, sum(CASE WHEN m.best_of = 5 THEN 1 ELSE 0 END) AS bo5_count",
          "__BLANK_1__": "team t JOIN match m ON m.winner_team_id = t.team_id",
          "__BLANK_2__": "t.team_id, t.name",
          "__BLANK_3__": "team_id"
        }
      },
      "hint": "Join to match before grouping; SUM over a CASE expression adds a conditional best-of-5 count.",
      "expectedSql": "SELECT t.team_id AS team_id, t.name AS team_name, count(m.match_id) AS match_count, sum(CASE WHEN m.best_of = 5 THEN 1 ELSE 0 END) AS bo5_count FROM team t JOIN match m ON m.winner_team_id = t.team_id GROUP BY t.team_id, t.name ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name",
          "match_count",
          "bo5_count"
        ],
        "rowCount": 34,
        "orderedRowHash": "bb522277548a4835c696a48f9f50c717d2352ffc3b28e6f39a4ba0edbbf29dae",
        "unorderedRowHash": "1e39bc79adf43e2fddad3be224f43441ac333fc895854f3808064a1fd426d5d8"
      }
    }
  ],
  "sl-join-inner": [
    {
      "id": "sl-join-inner-jzx6tp",
      "skill": "sl-join-inner",
      "database": "sideline",
      "task": "Join player to team and return player_id, handle, team_name for teams in region 5, ordered by player_id. Return columns: player_id, handle, team_name. Order by: player_id.",
      "starterSql": {
        "full": "SELECT p.player_id AS player_id, p.handle AS handle, t.name AS team_name FROM player p JOIN team t ON t.team_id = p.team_id WHERE t.region_id = __BLANK_0__ ORDER BY __BLANK_1__",
        "half": "SELECT p.player_id AS player_id, p.handle AS handle, t.name AS team_name FROM player p JOIN team t ON t.team_id = p.team_id WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "5",
          "__BLANK_1__": "player_id"
        },
        "half": {
          "__BLANK_0__": "t.region_id = 5",
          "__BLANK_1__": "player_id"
        },
        "blank": {
          "__BLANK_0__": "p.player_id AS player_id, p.handle AS handle, t.name AS team_name",
          "__BLANK_1__": "player p JOIN team t ON t.team_id = p.team_id",
          "__BLANK_2__": "t.region_id = 5",
          "__BLANK_3__": "player_id"
        }
      },
      "hint": "Inner JOIN player to team on team_id; free agents drop out because their team_id is NULL.",
      "expectedSql": "SELECT p.player_id AS player_id, p.handle AS handle, t.name AS team_name FROM player p JOIN team t ON t.team_id = p.team_id WHERE t.region_id = 5 ORDER BY player_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "player_id",
          "handle",
          "team_name"
        ],
        "rowCount": 32,
        "orderedRowHash": "db23ab6dc82cf80ddb809b211a06d5621f7e4a645324268bbf50aac22e528d25",
        "unorderedRowHash": "371ef4bb1f460a0b0b8147a368ff3dfee8cd8967ccf01aa4c4288be461a60f64"
      }
    }
  ],
  "sl-join-left": [
    {
      "id": "sl-join-left-1gjn84v",
      "skill": "sl-join-left",
      "database": "sideline",
      "task": "List every team sponsor row as team_id, team_name, sponsor_id, contract_start, and annual_value_usd, keeping sponsorless teams. Order by team_id, sponsor_id, contract_start. Return columns: team_id, team_name, sponsor_id, contract_start, annual_value_usd. Order by: team_id, sponsor_id, contract_start.",
      "starterSql": {
        "full": "SELECT t.team_id AS team_id, t.name AS team_name, ts.sponsor_id AS sponsor_id, ts.contract_start AS contract_start, ts.annual_value_usd AS annual_value_usd FROM team t LEFT JOIN team_sponsor ts ON ts.team_id = t.team_id ORDER BY __BLANK_0__, sponsor_id, contract_start",
        "half": "SELECT t.team_id AS team_id, t.name AS team_name, ts.sponsor_id AS sponsor_id, ts.contract_start AS contract_start, ts.annual_value_usd AS annual_value_usd FROM team t LEFT JOIN team_sponsor ts ON ts.team_id = t.team_id ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id"
        },
        "half": {
          "__BLANK_0__": "team_id, sponsor_id, contract_start"
        },
        "blank": {
          "__BLANK_0__": "t.team_id AS team_id, t.name AS team_name, ts.sponsor_id AS sponsor_id, ts.contract_start AS contract_start, ts.annual_value_usd AS annual_value_usd",
          "__BLANK_1__": "team t LEFT JOIN team_sponsor ts ON ts.team_id = t.team_id",
          "__BLANK_2__": "team_id, sponsor_id, contract_start"
        }
      },
      "hint": "LEFT JOIN keeps every team; sponsorless teams show NULL sponsor columns.",
      "expectedSql": "SELECT t.team_id AS team_id, t.name AS team_name, ts.sponsor_id AS sponsor_id, ts.contract_start AS contract_start, ts.annual_value_usd AS annual_value_usd FROM team t LEFT JOIN team_sponsor ts ON ts.team_id = t.team_id ORDER BY team_id, sponsor_id, contract_start",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name",
          "sponsor_id",
          "contract_start",
          "annual_value_usd"
        ],
        "rowCount": 127,
        "orderedRowHash": "914e5993dcf3d074fc3f3ff9444c05498d734ef4c40f88b03ac9f009ef666681",
        "unorderedRowHash": "35314acd054d2766401eee4648e2e0f49682c801f2ff9788d8fa9c42ac8251e5"
      }
    }
  ],
  "sl-join-multi": [
    {
      "id": "sl-join-multi-18osocr",
      "skill": "sl-join-multi",
      "database": "sideline",
      "task": "For tier B tournaments, list the first 3 rows as map_result_id, map_name, stage, and tournament_name. Order by map_result_id. Return columns: map_result_id, map_name, stage, tournament_name. Order by: map_result_id.",
      "starterSql": {
        "full": "SELECT mr.map_result_id AS map_result_id, mr.map_name AS map_name, m.stage AS stage, t.name AS tournament_name FROM map_result mr JOIN match m ON m.match_id = mr.match_id JOIN tournament t ON t.tournament_id = m.tournament_id WHERE t.tier = 'B' ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "half": "SELECT mr.map_result_id AS map_result_id, mr.map_name AS map_name, m.stage AS stage, t.name AS tournament_name FROM map_result mr JOIN match m ON m.match_id = mr.match_id JOIN tournament t ON t.tournament_id = m.tournament_id WHERE t.tier = 'B' ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "map_result_id",
          "__BLANK_1__": "3"
        },
        "half": {
          "__BLANK_0__": "map_result_id",
          "__BLANK_1__": "3"
        },
        "blank": {
          "__BLANK_0__": "mr.map_result_id AS map_result_id, mr.map_name AS map_name, m.stage AS stage, t.name AS tournament_name",
          "__BLANK_1__": "map_result mr JOIN match m ON m.match_id = mr.match_id JOIN tournament t ON t.tournament_id = m.tournament_id",
          "__BLANK_2__": "t.tier = 'B'",
          "__BLANK_3__": "map_result_id",
          "__BLANK_4__": "3"
        }
      },
      "hint": "Add one JOIN at a time: map_result to match, then match to tournament; LIMIT keeps the slice small.",
      "expectedSql": "SELECT mr.map_result_id AS map_result_id, mr.map_name AS map_name, m.stage AS stage, t.name AS tournament_name FROM map_result mr JOIN match m ON m.match_id = mr.match_id JOIN tournament t ON t.tournament_id = m.tournament_id WHERE t.tier = 'B' ORDER BY map_result_id LIMIT 3",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "map_result_id",
          "map_name",
          "stage",
          "tournament_name"
        ],
        "rowCount": 3,
        "orderedRowHash": "3a3ebc7cd24f806081897e0d225a3624e8e3ac60bb2fbdbdcf2b54a59a22846b",
        "unorderedRowHash": "3a3ebc7cd24f806081897e0d225a3624e8e3ac60bb2fbdbdcf2b54a59a22846b"
      }
    }
  ],
  "sl-join-right-full": [
    {
      "id": "sl-join-right-full-f61mfu",
      "skill": "sl-join-right-full",
      "database": "sideline",
      "task": "Show the outer edge of team versus team_sponsor: rows where one side is NULL. Return team_id, team_name, sponsor_id, ordered by team_id. Return columns: team_id, team_name, sponsor_id. Order by: team_id.",
      "starterSql": {
        "full": "SELECT t.team_id AS team_id, t.name AS team_name, ts.sponsor_id AS sponsor_id FROM team t FULL OUTER JOIN team_sponsor ts ON ts.team_id = t.team_id WHERE t.team_id IS NULL OR ts.sponsor_id IS NULL ORDER BY __BLANK_0__",
        "half": "SELECT t.team_id AS team_id, t.name AS team_name, ts.sponsor_id AS sponsor_id FROM team t FULL OUTER JOIN team_sponsor ts ON ts.team_id = t.team_id WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id"
        },
        "half": {
          "__BLANK_0__": "t.team_id IS NULL OR ts.sponsor_id IS NULL",
          "__BLANK_1__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "t.team_id AS team_id, t.name AS team_name, ts.sponsor_id AS sponsor_id",
          "__BLANK_1__": "team t FULL OUTER JOIN team_sponsor ts ON ts.team_id = t.team_id",
          "__BLANK_2__": "t.team_id IS NULL OR ts.sponsor_id IS NULL",
          "__BLANK_3__": "team_id"
        }
      },
      "hint": "FULL OUTER JOIN keeps unmatched rows, then the WHERE clause filters to only those unmatched cases.",
      "expectedSql": "SELECT t.team_id AS team_id, t.name AS team_name, ts.sponsor_id AS sponsor_id FROM team t FULL OUTER JOIN team_sponsor ts ON ts.team_id = t.team_id WHERE t.team_id IS NULL OR ts.sponsor_id IS NULL ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name",
          "sponsor_id"
        ],
        "rowCount": 7,
        "orderedRowHash": "d8bc37bd9de4639146d7173a04c21f96e725b479371c5c06c4c95260959fb1e6",
        "unorderedRowHash": "924d0f663c7c64a651ce3507a82d19095b92551dbe1f784baf50f76744b4daf3"
      }
    }
  ],
  "sl-scd-asof": [
    {
      "id": "sl-scd-asof-ka4hrr",
      "skill": "sl-scd-asof",
      "database": "sideline",
      "task": "As of 2025-01-01, list the first 3 active roster stints as roster_change_id, player_id, team_id, and from_date. Order by roster_change_id. Return columns: roster_change_id, player_id, team_id, from_date. Order by: roster_change_id.",
      "starterSql": {
        "full": "SELECT rc.roster_change_id AS roster_change_id, rc.player_id AS player_id, rc.team_id AS team_id, rc.from_date AS from_date FROM roster_change rc WHERE rc.from_date <= DATE '2025-01-01' AND (rc.to_date IS NULL OR rc.to_date > DATE '2025-01-01') ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "half": "SELECT rc.roster_change_id AS roster_change_id, rc.player_id AS player_id, rc.team_id AS team_id, rc.from_date AS from_date FROM roster_change rc WHERE rc.from_date <= DATE '2025-01-01' AND (rc.to_date IS NULL OR rc.to_date > DATE '2025-01-01') ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "roster_change_id",
          "__BLANK_1__": "3"
        },
        "half": {
          "__BLANK_0__": "roster_change_id",
          "__BLANK_1__": "3"
        },
        "blank": {
          "__BLANK_0__": "rc.roster_change_id AS roster_change_id, rc.player_id AS player_id, rc.team_id AS team_id, rc.from_date AS from_date",
          "__BLANK_1__": "roster_change rc",
          "__BLANK_2__": "rc.from_date <= DATE '2025-01-01' AND (rc.to_date IS NULL OR rc.to_date > DATE '2025-01-01')",
          "__BLANK_3__": "roster_change_id",
          "__BLANK_4__": "3"
        }
      },
      "hint": "The active stint has from_date on or before the as-of date and either an open to_date or a later to_date.",
      "expectedSql": "SELECT rc.roster_change_id AS roster_change_id, rc.player_id AS player_id, rc.team_id AS team_id, rc.from_date AS from_date FROM roster_change rc WHERE rc.from_date <= DATE '2025-01-01' AND (rc.to_date IS NULL OR rc.to_date > DATE '2025-01-01') ORDER BY roster_change_id LIMIT 3",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "roster_change_id",
          "player_id",
          "team_id",
          "from_date"
        ],
        "rowCount": 3,
        "orderedRowHash": "11cb00da0658a18e4fc0b2d02a0048baea5c71b09b6c30db21306f936b07e9e7",
        "unorderedRowHash": "11cb00da0658a18e4fc0b2d02a0048baea5c71b09b6c30db21306f936b07e9e7"
      }
    }
  ],
  "sl-self-join-compare": [
    {
      "id": "sl-self-join-compare-1vjg74u",
      "skill": "sl-self-join-compare",
      "database": "sideline",
      "task": "Self-join team on region_id and elo_rating and return team_id, team_a_name, team_b_name for each pair, ordered by team_id. Return columns: team_id, team_a_name, team_b_name. Order by: team_id.",
      "starterSql": {
        "full": "SELECT a.team_id AS team_id, a.name AS team_a_name, b.name AS team_b_name FROM team a JOIN team b ON a.region_id = b.region_id AND a.elo_rating = b.elo_rating AND a.team_id < b.team_id ORDER BY __BLANK_0__",
        "half": "SELECT a.team_id AS team_id, a.name AS team_a_name, b.name AS team_b_name FROM team a JOIN team b ON a.region_id = b.region_id AND a.elo_rating = b.elo_rating AND a.team_id < b.team_id ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id"
        },
        "half": {
          "__BLANK_0__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "a.team_id AS team_id, a.name AS team_a_name, b.name AS team_b_name",
          "__BLANK_1__": "team a JOIN team b ON a.region_id = b.region_id AND a.elo_rating = b.elo_rating AND a.team_id < b.team_id",
          "__BLANK_2__": "team_id"
        }
      },
      "hint": "Join team to itself; the a.team_id < b.team_id guard removes self-pairs and mirrored duplicates.",
      "expectedSql": "SELECT a.team_id AS team_id, a.name AS team_a_name, b.name AS team_b_name FROM team a JOIN team b ON a.region_id = b.region_id AND a.elo_rating = b.elo_rating AND a.team_id < b.team_id ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_a_name",
          "team_b_name"
        ],
        "rowCount": 1,
        "orderedRowHash": "092ce28bbdffbee9876973ce1de179d8ee7aa28d46e056b6cd74c35b4ab2e976",
        "unorderedRowHash": "092ce28bbdffbee9876973ce1de179d8ee7aa28d46e056b6cd74c35b4ab2e976"
      }
    }
  ],
  "sl-self-join-match": [
    {
      "id": "sl-self-join-match-12ej3o7",
      "skill": "sl-self-join-match",
      "database": "sideline",
      "task": "Show 3 Grand Final matches as match_id, winner_name, loser_name by joining team twice. Order by match_id. Return columns: match_id, winner_name, loser_name. Order by: match_id.",
      "starterSql": {
        "full": "SELECT m.match_id AS match_id, w.name AS winner_name, l.name AS loser_name FROM match m\nJOIN team w ON w.team_id = m.winner_team_id\nJOIN team l ON l.team_id = CASE WHEN m.winner_team_id = m.team_a_id THEN m.team_b_id ELSE m.team_a_id END\nWHERE m.stage = 'Grand Final' ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "half": "SELECT m.match_id AS match_id, w.name AS winner_name, l.name AS loser_name FROM match m\nJOIN team w ON w.team_id = m.winner_team_id\nJOIN team l ON l.team_id = CASE WHEN m.winner_team_id = m.team_a_id THEN m.team_b_id ELSE m.team_a_id END\nWHERE m.stage = 'Grand Final' ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "match_id",
          "__BLANK_1__": "3"
        },
        "half": {
          "__BLANK_0__": "match_id",
          "__BLANK_1__": "3"
        },
        "blank": {
          "__BLANK_0__": "m.match_id AS match_id, w.name AS winner_name, l.name AS loser_name",
          "__BLANK_1__": "match m\nJOIN team w ON w.team_id = m.winner_team_id\nJOIN team l ON l.team_id = CASE WHEN m.winner_team_id = m.team_a_id THEN m.team_b_id ELSE m.team_a_id END",
          "__BLANK_2__": "m.stage = 'Grand Final'",
          "__BLANK_3__": "match_id",
          "__BLANK_4__": "3"
        }
      },
      "hint": "Join match to team twice with aliases. One join is on winner_team_id; the other uses CASE to choose the non-winning team id.",
      "expectedSql": "SELECT m.match_id AS match_id, w.name AS winner_name, l.name AS loser_name FROM match m\nJOIN team w ON w.team_id = m.winner_team_id\nJOIN team l ON l.team_id = CASE WHEN m.winner_team_id = m.team_a_id THEN m.team_b_id ELSE m.team_a_id END\nWHERE m.stage = 'Grand Final' ORDER BY match_id LIMIT 3",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "match_id",
          "winner_name",
          "loser_name"
        ],
        "rowCount": 3,
        "orderedRowHash": "f540963ab249613a902201823f87b6853c459faeb2e4e5bff1f778173cdc2b78",
        "unorderedRowHash": "f540963ab249613a902201823f87b6853c459faeb2e4e5bff1f778173cdc2b78"
      }
    }
  ],
  "sl-semi-join": [
    {
      "id": "sl-semi-join-flu8sg",
      "skill": "sl-semi-join",
      "database": "sideline",
      "task": "Use EXISTS against team_sponsor to return sponsored teams as team_id, team_name, ordered by team_id. Return columns: team_id, team_name. Order by: team_id.",
      "starterSql": {
        "full": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t WHERE EXISTS (SELECT 1 FROM team_sponsor ts WHERE ts.team_id = t.team_id) ORDER BY __BLANK_0__",
        "half": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id"
        },
        "half": {
          "__BLANK_0__": "EXISTS (SELECT 1 FROM team_sponsor ts WHERE ts.team_id = t.team_id)",
          "__BLANK_1__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "t.team_id AS team_id, t.name AS team_name",
          "__BLANK_1__": "team t",
          "__BLANK_2__": "EXISTS (SELECT 1 FROM team_sponsor ts WHERE ts.team_id = t.team_id)",
          "__BLANK_3__": "team_id"
        }
      },
      "hint": "EXISTS returns each team once even when multiple sponsor rows match.",
      "expectedSql": "SELECT t.team_id AS team_id, t.name AS team_name FROM team t WHERE EXISTS (SELECT 1 FROM team_sponsor ts WHERE ts.team_id = t.team_id) ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name"
        ],
        "rowCount": 33,
        "orderedRowHash": "530f4232b99d248ba474992bfbd7cc5ac6c090645c77981c255b4ae3272c6bfd",
        "unorderedRowHash": "d6bbc68b073e2e955d74020ec1519ab3bead2cddeb569a5815ebdd8ad4fbfbf2"
      }
    }
  ],
  "sl-set-ops": [
    {
      "id": "sl-set-ops-1y3hpwj",
      "skill": "sl-set-ops",
      "database": "sideline",
      "task": "UNION tournament host_country with player country into one country column and return the distinct non-NULL values ordered by country. Return columns: country. Order by: country.",
      "starterSql": {
        "full": "SELECT DISTINCT __BLANK_0__ AS country FROM (SELECT host_country AS country FROM tournament UNION SELECT __BLANK_1__ AS country FROM player) countries WHERE __BLANK_2__ IS NOT NULL ORDER BY __BLANK_3__",
        "half": "SELECT DISTINCT country AS country FROM (SELECT host_country AS country FROM tournament UNION SELECT country AS country FROM player) countries WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "country",
          "__BLANK_1__": "country",
          "__BLANK_2__": "country",
          "__BLANK_3__": "country"
        },
        "half": {
          "__BLANK_0__": "country IS NOT NULL",
          "__BLANK_1__": "country"
        },
        "blank": {
          "__BLANK_0__": "DISTINCT country AS country",
          "__BLANK_1__": "(SELECT host_country AS country FROM tournament UNION SELECT country AS country FROM player) countries",
          "__BLANK_2__": "country IS NOT NULL",
          "__BLANK_3__": "country"
        }
      },
      "hint": "Both SELECTs inside the UNION expose one text column named country; the outer query removes NULL.",
      "expectedSql": "SELECT DISTINCT country AS country FROM (SELECT host_country AS country FROM tournament UNION SELECT country AS country FROM player) countries WHERE country IS NOT NULL ORDER BY country",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "country"
        ],
        "rowCount": 19,
        "orderedRowHash": "1d950da68032b87629aafa0f09e10d198a34fbfb462e5f2dce0038c326536308",
        "unorderedRowHash": "1d950da68032b87629aafa0f09e10d198a34fbfb462e5f2dce0038c326536308"
      }
    }
  ],
  "sl-subquery-correlated": [
    {
      "id": "sl-subquery-correlated-16gr93z",
      "skill": "sl-subquery-correlated",
      "database": "sideline",
      "task": "List rostered players who earn more than their own team average. Return player_id and handle. Order by player_id. Return columns: player_id, handle. Order by: player_id.",
      "starterSql": {
        "full": "SELECT p.player_id AS player_id, p.handle AS handle FROM player p WHERE p.team_id IS NOT NULL AND p.total_earnings_usd > (SELECT avg(p2.total_earnings_usd) FROM player p2 WHERE p2.team_id = p.team_id) ORDER BY __BLANK_0__",
        "half": "SELECT p.player_id AS player_id, p.handle AS handle FROM player p WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "player_id"
        },
        "half": {
          "__BLANK_0__": "p.team_id IS NOT NULL AND p.total_earnings_usd > (SELECT avg(p2.total_earnings_usd) FROM player p2 WHERE p2.team_id = p.team_id)",
          "__BLANK_1__": "player_id"
        },
        "blank": {
          "__BLANK_0__": "p.player_id AS player_id, p.handle AS handle",
          "__BLANK_1__": "player p",
          "__BLANK_2__": "p.team_id IS NOT NULL AND p.total_earnings_usd > (SELECT avg(p2.total_earnings_usd) FROM player p2 WHERE p2.team_id = p.team_id)",
          "__BLANK_3__": "player_id"
        }
      },
      "hint": "The inner query references the outer p.team_id, so it recomputes for each player.",
      "expectedSql": "SELECT p.player_id AS player_id, p.handle AS handle FROM player p WHERE p.team_id IS NOT NULL AND p.total_earnings_usd > (SELECT avg(p2.total_earnings_usd) FROM player p2 WHERE p2.team_id = p.team_id) ORDER BY player_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "player_id",
          "handle"
        ],
        "rowCount": 115,
        "orderedRowHash": "e26aee178b3a20252a49146aab3fe4ebf261d56bc96e0e7f798ddeb54f42efbf",
        "unorderedRowHash": "4e53ee4f342bee567499686f9647155d96757f0ddfb6abc614fc49b62cba1aee"
      }
    }
  ],
  "sl-subquery-in": [
    {
      "id": "sl-subquery-in-1sgfn9z",
      "skill": "sl-subquery-in",
      "database": "sideline",
      "task": "List teams in regions that host at least one tier A tournament. Return team_id and team_name. Order by team_id. Return columns: team_id, team_name. Order by: team_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS team_id, name AS team_name FROM team WHERE region_id IN (SELECT region_id FROM tournament WHERE tier = 'A' AND region_id IS NOT NULL) ORDER BY __BLANK_1__",
        "half": "SELECT team_id AS team_id, name AS team_name FROM team WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id",
          "__BLANK_1__": "team_id"
        },
        "half": {
          "__BLANK_0__": "region_id IN (SELECT region_id FROM tournament WHERE tier = 'A' AND region_id IS NOT NULL)",
          "__BLANK_1__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "team_id AS team_id, name AS team_name",
          "__BLANK_1__": "team",
          "__BLANK_2__": "region_id IN (SELECT region_id FROM tournament WHERE tier = 'A' AND region_id IS NOT NULL)",
          "__BLANK_3__": "team_id"
        }
      },
      "hint": "Build the set of region_id values inside the subquery, then keep teams whose region_id is IN that set.",
      "expectedSql": "SELECT team_id AS team_id, name AS team_name FROM team WHERE region_id IN (SELECT region_id FROM tournament WHERE tier = 'A' AND region_id IS NOT NULL) ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name"
        ],
        "rowCount": 21,
        "orderedRowHash": "7b1dc756bba73ef00b566d5630df090ec282aecabcbc9390d7a1e50ff3d74895",
        "unorderedRowHash": "aefe94785ba0fde6be897f9dfab5c758ea6b22de36b5538406a22697a22b7e99"
      }
    }
  ],
  "sl-subquery-scalar": [
    {
      "id": "sl-subquery-scalar-nsdjb0",
      "skill": "sl-subquery-scalar",
      "database": "sideline",
      "task": "Compare each team to the scalar average Elo subquery and return team_id, team_name, elo_rating for the above-average teams, ordered by team_id. Return columns: team_id, team_name, elo_rating. Order by: team_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS team_id, name AS team_name, elo_rating AS elo_rating FROM team WHERE elo_rating > (SELECT avg(elo_rating) FROM team) ORDER BY __BLANK_1__",
        "half": "SELECT team_id AS team_id, name AS team_name, elo_rating AS elo_rating FROM team WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id",
          "__BLANK_1__": "team_id"
        },
        "half": {
          "__BLANK_0__": "elo_rating > (SELECT avg(elo_rating) FROM team)",
          "__BLANK_1__": "team_id"
        },
        "blank": {
          "__BLANK_0__": "team_id AS team_id, name AS team_name, elo_rating AS elo_rating",
          "__BLANK_1__": "team",
          "__BLANK_2__": "elo_rating > (SELECT avg(elo_rating) FROM team)",
          "__BLANK_3__": "team_id"
        }
      },
      "hint": "A scalar subquery in parentheses returns one number you can compare against.",
      "expectedSql": "SELECT team_id AS team_id, name AS team_name, elo_rating AS elo_rating FROM team WHERE elo_rating > (SELECT avg(elo_rating) FROM team) ORDER BY team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name",
          "elo_rating"
        ],
        "rowCount": 19,
        "orderedRowHash": "39aea2e6ed0ea3c87337e1f85ba6369742c6ab1b9199d4b9e2e948260b5785c0",
        "unorderedRowHash": "ec0c847a991a02204898e181ae213baa1fded43c74afc39a24641e8a05b25004"
      }
    }
  ],
  "sl-window-frame-basic": [
    {
      "id": "sl-window-frame-basic-xaq678",
      "skill": "sl-window-frame-basic",
      "database": "sideline",
      "task": "Use AVG(prize_pool_usd) over a ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING frame and return tournament_id, region_id, start_date, prize_pool_usd, smoothed_prize, ordered by region_id and tournament_id. Return columns: tournament_id, region_id, start_date, prize_pool_usd, smoothed_prize. Order by: region_id, tournament_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS tournament_id, __BLANK_1__ AS region_id, start_date AS start_date, prize_pool_usd AS prize_pool_usd, ROUND(AVG(prize_pool_usd) OVER (PARTITION BY __BLANK_2__ ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), 2) AS smoothed_prize FROM tournament WHERE __BLANK_3__ IS NOT NULL ORDER BY __BLANK_4__, __BLANK_5__",
        "half": "SELECT tournament_id AS tournament_id, region_id AS region_id, start_date AS start_date, prize_pool_usd AS prize_pool_usd, ROUND(AVG(prize_pool_usd) OVER (PARTITION BY region_id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), 2) AS smoothed_prize FROM tournament WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "tournament_id",
          "__BLANK_1__": "region_id",
          "__BLANK_2__": "region_id",
          "__BLANK_3__": "region_id",
          "__BLANK_4__": "region_id",
          "__BLANK_5__": "tournament_id"
        },
        "half": {
          "__BLANK_0__": "region_id IS NOT NULL",
          "__BLANK_1__": "region_id, tournament_id"
        },
        "blank": {
          "__BLANK_0__": "tournament_id AS tournament_id, region_id AS region_id, start_date AS start_date, prize_pool_usd AS prize_pool_usd, ROUND(AVG(prize_pool_usd) OVER (PARTITION BY region_id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), 2) AS smoothed_prize",
          "__BLANK_1__": "tournament",
          "__BLANK_2__": "region_id IS NOT NULL",
          "__BLANK_3__": "region_id, tournament_id"
        }
      },
      "hint": "The ROWS BETWEEN frame slides over nearby rows in the same region partition; emit wraps AVG with ROUND.",
      "expectedSql": "SELECT tournament_id AS tournament_id, region_id AS region_id, start_date AS start_date, prize_pool_usd AS prize_pool_usd, ROUND(AVG(prize_pool_usd) OVER (PARTITION BY region_id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), 2) AS smoothed_prize FROM tournament WHERE region_id IS NOT NULL ORDER BY region_id, tournament_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "tournament_id",
          "region_id",
          "start_date",
          "prize_pool_usd",
          "smoothed_prize"
        ],
        "rowCount": 16,
        "orderedRowHash": "09be6e46ec9ab235e4a36fddc140482d77b28c9e6313a5ccbac767e7cc1107a7",
        "unorderedRowHash": "b9cbe187dd33c00e0126701e526c7af35347e6c2cf6167dff1ab70501cb2657c"
      }
    }
  ],
  "sl-window-lag-lead": [
    {
      "id": "sl-window-lag-lead-9umq43",
      "skill": "sl-window-lag-lead",
      "database": "sideline",
      "task": "For each region partition, show each tournament with prev_start from LAG(start_date). Return tournament_id, region_id, name, start_date, prev_start. Order by region_id and tournament_id. Return columns: tournament_id, region_id, name, start_date, prev_start. Order by: region_id, tournament_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS tournament_id, __BLANK_1__ AS region_id, name AS name, start_date AS start_date, LAG(start_date) OVER (PARTITION BY __BLANK_2__) AS prev_start FROM tournament WHERE __BLANK_3__ IS NOT NULL ORDER BY __BLANK_4__, __BLANK_5__",
        "half": "SELECT tournament_id AS tournament_id, region_id AS region_id, name AS name, start_date AS start_date, LAG(start_date) OVER (PARTITION BY region_id) AS prev_start FROM tournament WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "tournament_id",
          "__BLANK_1__": "region_id",
          "__BLANK_2__": "region_id",
          "__BLANK_3__": "region_id",
          "__BLANK_4__": "region_id",
          "__BLANK_5__": "tournament_id"
        },
        "half": {
          "__BLANK_0__": "region_id IS NOT NULL",
          "__BLANK_1__": "region_id, tournament_id"
        },
        "blank": {
          "__BLANK_0__": "tournament_id AS tournament_id, region_id AS region_id, name AS name, start_date AS start_date, LAG(start_date) OVER (PARTITION BY region_id) AS prev_start",
          "__BLANK_1__": "tournament",
          "__BLANK_2__": "region_id IS NOT NULL",
          "__BLANK_3__": "region_id, tournament_id"
        }
      },
      "hint": "LAG reads the previous row in the same region partition; the first row per partition returns NULL.",
      "expectedSql": "SELECT tournament_id AS tournament_id, region_id AS region_id, name AS name, start_date AS start_date, LAG(start_date) OVER (PARTITION BY region_id) AS prev_start FROM tournament WHERE region_id IS NOT NULL ORDER BY region_id, tournament_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "tournament_id",
          "region_id",
          "name",
          "start_date",
          "prev_start"
        ],
        "rowCount": 16,
        "orderedRowHash": "6ac82f385e43e62c483d7254c0f248574645ca02c402e604793a5beef3668db0",
        "unorderedRowHash": "e9633a18eb96637dc47264ef6616a8386ef84ebafe5ffcbc8374e0b1036eb822"
      }
    }
  ],
  "sl-window-rank": [
    {
      "id": "sl-window-rank-3v9cju",
      "skill": "sl-window-rank",
      "database": "sideline",
      "task": "Use RANK() with PARTITION BY region_id and return team_id, team_name, region_id, elo_rating, region_rank, ordered by region_id and team_id. Return columns: team_id, team_name, region_id, elo_rating, region_rank. Order by: region_id, team_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS team_id, name AS team_name, __BLANK_1__ AS region_id, elo_rating AS elo_rating, RANK() OVER (PARTITION BY __BLANK_2__) AS region_rank FROM team ORDER BY __BLANK_3__, __BLANK_4__",
        "half": "SELECT team_id AS team_id, name AS team_name, region_id AS region_id, elo_rating AS elo_rating, RANK() OVER (PARTITION BY region_id) AS region_rank FROM team ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "team_id",
          "__BLANK_1__": "region_id",
          "__BLANK_2__": "region_id",
          "__BLANK_3__": "region_id",
          "__BLANK_4__": "team_id"
        },
        "half": {
          "__BLANK_0__": "region_id, team_id"
        },
        "blank": {
          "__BLANK_0__": "team_id AS team_id, name AS team_name, region_id AS region_id, elo_rating AS elo_rating, RANK() OVER (PARTITION BY region_id) AS region_rank",
          "__BLANK_1__": "team",
          "__BLANK_2__": "region_id, team_id"
        }
      },
      "hint": "PARTITION BY region_id restarts the window calculation for each region; team_id is the final deterministic tiebreak.",
      "expectedSql": "SELECT team_id AS team_id, name AS team_name, region_id AS region_id, elo_rating AS elo_rating, RANK() OVER (PARTITION BY region_id) AS region_rank FROM team ORDER BY region_id, team_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "team_id",
          "team_name",
          "region_id",
          "elo_rating",
          "region_rank"
        ],
        "rowCount": 40,
        "orderedRowHash": "c1bca748e67ddec0397b0eb08cf56b6b01d10affd1ead9596e19548b30cd3469",
        "unorderedRowHash": "72bfbcee76e31c847486185cb16ac306ce7d55d5e92dfa95fc4cb5262dbe8fb3"
      }
    }
  ],
  "sl-window-running": [
    {
      "id": "sl-window-running-1sl5ail",
      "skill": "sl-window-running",
      "database": "sideline",
      "task": "For each region partition, calculate running_prize with a windowed SUM. Return tournament_id, region_id, name, prize_pool_usd, running_prize. Order by region_id and tournament_id. Return columns: tournament_id, region_id, name, prize_pool_usd, running_prize. Order by: region_id, tournament_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS tournament_id, __BLANK_1__ AS region_id, name AS name, prize_pool_usd AS prize_pool_usd, SUM(prize_pool_usd) OVER (PARTITION BY __BLANK_2__) AS running_prize FROM tournament WHERE __BLANK_3__ IS NOT NULL ORDER BY __BLANK_4__, __BLANK_5__",
        "half": "SELECT tournament_id AS tournament_id, region_id AS region_id, name AS name, prize_pool_usd AS prize_pool_usd, SUM(prize_pool_usd) OVER (PARTITION BY region_id) AS running_prize FROM tournament WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "tournament_id",
          "__BLANK_1__": "region_id",
          "__BLANK_2__": "region_id",
          "__BLANK_3__": "region_id",
          "__BLANK_4__": "region_id",
          "__BLANK_5__": "tournament_id"
        },
        "half": {
          "__BLANK_0__": "region_id IS NOT NULL",
          "__BLANK_1__": "region_id, tournament_id"
        },
        "blank": {
          "__BLANK_0__": "tournament_id AS tournament_id, region_id AS region_id, name AS name, prize_pool_usd AS prize_pool_usd, SUM(prize_pool_usd) OVER (PARTITION BY region_id) AS running_prize",
          "__BLANK_1__": "tournament",
          "__BLANK_2__": "region_id IS NOT NULL",
          "__BLANK_3__": "region_id, tournament_id"
        }
      },
      "hint": "A windowed SUM keeps each tournament row while adding a partition-level prize calculation.",
      "expectedSql": "SELECT tournament_id AS tournament_id, region_id AS region_id, name AS name, prize_pool_usd AS prize_pool_usd, SUM(prize_pool_usd) OVER (PARTITION BY region_id) AS running_prize FROM tournament WHERE region_id IS NOT NULL ORDER BY region_id, tournament_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "tournament_id",
          "region_id",
          "name",
          "prize_pool_usd",
          "running_prize"
        ],
        "rowCount": 16,
        "orderedRowHash": "8abe1ebe3925c3ae99ef4df7c3eeaa12a5c167f0e8ce6f5c1b60f05990c6e017",
        "unorderedRowHash": "6ba4a65c351ae3f28f045fb8e8f7de7bae817e2a7d4981eff7413ca3afb2f2ea"
      }
    }
  ]
};
