// AUTO-GENERATED by scripts/generate-exercises.ts. DO NOT EDIT BY HAND.
// Regenerate with: npm run generate-exercises
import type { Exercise } from '../../generator/types';

export const GENERATED_EXERCISES: Record<string, Exercise[]> = {
  "rv-case-canonicalize": [
    {
      "id": "rv-case-canonicalize-ytmd2e",
      "skill": "rv-case-canonicalize",
      "database": "rove",
      "task": "For city 7, return payment_id, order_id, and canonical_method after mapping method synonyms. Return columns: payment_id, order_id, canonical_method. Order by: payment_id.",
      "starterSql": {
        "full": "SELECT\n  p.payment_id AS payment_id, p.order_id AS order_id, CASE\n    WHEN LOWER(TRIM(p.method)) IN ('cc', 'credit', 'credit card') THEN 'credit_card'\n    WHEN LOWER(TRIM(p.method)) IN ('applepay', 'apple pay') THEN 'apple_pay'\n    ELSE LOWER(TRIM(p.method))\n  END AS canonical_method FROM payments p\nJOIN orders o ON o.order_id = p.order_id\nWHERE o.city_id = __BLANK_0__ ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  p.payment_id AS payment_id, p.order_id AS order_id, CASE\n    WHEN LOWER(TRIM(p.method)) IN ('cc', 'credit', 'credit card') THEN 'credit_card'\n    WHEN LOWER(TRIM(p.method)) IN ('applepay', 'apple pay') THEN 'apple_pay'\n    ELSE LOWER(TRIM(p.method))\n  END AS canonical_method FROM payments p\nJOIN orders o ON o.order_id = p.order_id\nWHERE o.city_id = 7 ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "7",
          "__BLANK_1__": "payment_id"
        },
        "half": {
          "__BLANK_0__": "payment_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "p.payment_id AS payment_id, p.order_id AS order_id, CASE\n    WHEN LOWER(TRIM(p.method)) IN ('cc', 'credit', 'credit card') THEN 'credit_card'\n    WHEN LOWER(TRIM(p.method)) IN ('applepay', 'apple pay') THEN 'apple_pay'\n    ELSE LOWER(TRIM(p.method))\n  END AS canonical_method",
          "__BLANK_1__": "payments p\nJOIN orders o ON o.order_id = p.order_id",
          "__BLANK_2__": "o.city_id = 7",
          "__BLANK_3__": "payment_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "Lowercase and trim first, then map synonym groups with a CASE ladder.",
      "expectedSql": "SELECT\n  p.payment_id AS payment_id, p.order_id AS order_id, CASE\n    WHEN LOWER(TRIM(p.method)) IN ('cc', 'credit', 'credit card') THEN 'credit_card'\n    WHEN LOWER(TRIM(p.method)) IN ('applepay', 'apple pay') THEN 'apple_pay'\n    ELSE LOWER(TRIM(p.method))\n  END AS canonical_method FROM payments p\nJOIN orders o ON o.order_id = p.order_id\nWHERE o.city_id = 7 ORDER BY payment_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "payment_id",
          "order_id",
          "canonical_method"
        ],
        "rowCount": 200,
        "orderedRowHash": "8e0bff70bc6185a6678cd95ef3ba0d170757e3b88048a4547d392658024ad567",
        "unorderedRowHash": "8e0bff70bc6185a6678cd95ef3ba0d170757e3b88048a4547d392658024ad567"
      }
    }
  ],
  "rv-clean-layer-capstone": [
    {
      "id": "rv-clean-layer-capstone-2v5ucb",
      "skill": "rv-clean-layer-capstone",
      "database": "rove",
      "task": "Stack clean-layer subqueries and report merchant_id, order_count, gross_cents, delivered_orders. Return columns: merchant_id, order_count, gross_cents, delivered_orders. Order by: merchant_id.",
      "starterSql": {
        "full": "SELECT\n  canon.merchant_id AS merchant_id, COUNT(*) AS order_count, SUM(canon.amount_cents) AS gross_cents, COUNT(*) FILTER (WHERE canon.clean_status = 'delivered') AS delivered_orders FROM (\n  SELECT\n    o.order_id,\n    o.merchant_id,\n    dp.amount_cents,\n    CASE\n      WHEN LOWER(TRIM(o.status)) IN ('delivered', 'complete') THEN 'delivered'\n      ELSE LOWER(TRIM(o.status))\n    END AS clean_status\n  FROM orders o\n  JOIN (SELECT customer_id FROM customers WHERE is_deleted = false) valid_customers\n    ON valid_customers.customer_id = o.customer_id\n  JOIN (\n    SELECT\n      chosen.order_id,\n      chosen.amount_cents\n    FROM (\n      SELECT\n        p.order_id,\n        p.amount_cents,\n        MIN(p.payment_id) OVER (PARTITION BY p.order_id) AS chosen_payment_id,\n        p.payment_id\n      FROM payments p\n    ) chosen\n    WHERE chosen.payment_id = chosen.chosen_payment_id\n  ) dp ON dp.order_id = o.order_id\n) canon\nGROUP BY canon.merchant_id ORDER BY __BLANK_0__ LIMIT 200",
        "half": "SELECT\n  canon.merchant_id AS merchant_id, COUNT(*) AS order_count, SUM(canon.amount_cents) AS gross_cents, COUNT(*) FILTER (WHERE canon.clean_status = 'delivered') AS delivered_orders FROM (\n  SELECT\n    o.order_id,\n    o.merchant_id,\n    dp.amount_cents,\n    CASE\n      WHEN LOWER(TRIM(o.status)) IN ('delivered', 'complete') THEN 'delivered'\n      ELSE LOWER(TRIM(o.status))\n    END AS clean_status\n  FROM orders o\n  JOIN (SELECT customer_id FROM customers WHERE is_deleted = false) valid_customers\n    ON valid_customers.customer_id = o.customer_id\n  JOIN (\n    SELECT\n      chosen.order_id,\n      chosen.amount_cents\n    FROM (\n      SELECT\n        p.order_id,\n        p.amount_cents,\n        MIN(p.payment_id) OVER (PARTITION BY p.order_id) AS chosen_payment_id,\n        p.payment_id\n      FROM payments p\n    ) chosen\n    WHERE chosen.payment_id = chosen.chosen_payment_id\n  ) dp ON dp.order_id = o.order_id\n) canon\nGROUP BY canon.merchant_id ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nGROUP BY __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "merchant_id"
        },
        "half": {
          "__BLANK_0__": "merchant_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "canon.merchant_id AS merchant_id, COUNT(*) AS order_count, SUM(canon.amount_cents) AS gross_cents, COUNT(*) FILTER (WHERE canon.clean_status = 'delivered') AS delivered_orders",
          "__BLANK_1__": "(\n  SELECT\n    o.order_id,\n    o.merchant_id,\n    dp.amount_cents,\n    CASE\n      WHEN LOWER(TRIM(o.status)) IN ('delivered', 'complete') THEN 'delivered'\n      ELSE LOWER(TRIM(o.status))\n    END AS clean_status\n  FROM orders o\n  JOIN (SELECT customer_id FROM customers WHERE is_deleted = false) valid_customers\n    ON valid_customers.customer_id = o.customer_id\n  JOIN (\n    SELECT\n      chosen.order_id,\n      chosen.amount_cents\n    FROM (\n      SELECT\n        p.order_id,\n        p.amount_cents,\n        MIN(p.payment_id) OVER (PARTITION BY p.order_id) AS chosen_payment_id,\n        p.payment_id\n      FROM payments p\n    ) chosen\n    WHERE chosen.payment_id = chosen.chosen_payment_id\n  ) dp ON dp.order_id = o.order_id\n) canon",
          "__BLANK_2__": "canon.merchant_id",
          "__BLANK_3__": "merchant_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "Compose the trusted layer from valid customers, one payment per order, and canonical status, then aggregate the bounded city slice.",
      "expectedSql": "SELECT\n  canon.merchant_id AS merchant_id, COUNT(*) AS order_count, SUM(canon.amount_cents) AS gross_cents, COUNT(*) FILTER (WHERE canon.clean_status = 'delivered') AS delivered_orders FROM (\n  SELECT\n    o.order_id,\n    o.merchant_id,\n    dp.amount_cents,\n    CASE\n      WHEN LOWER(TRIM(o.status)) IN ('delivered', 'complete') THEN 'delivered'\n      ELSE LOWER(TRIM(o.status))\n    END AS clean_status\n  FROM orders o\n  JOIN (SELECT customer_id FROM customers WHERE is_deleted = false) valid_customers\n    ON valid_customers.customer_id = o.customer_id\n  JOIN (\n    SELECT\n      chosen.order_id,\n      chosen.amount_cents\n    FROM (\n      SELECT\n        p.order_id,\n        p.amount_cents,\n        MIN(p.payment_id) OVER (PARTITION BY p.order_id) AS chosen_payment_id,\n        p.payment_id\n      FROM payments p\n    ) chosen\n    WHERE chosen.payment_id = chosen.chosen_payment_id\n  ) dp ON dp.order_id = o.order_id\n) canon\nGROUP BY canon.merchant_id ORDER BY merchant_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "merchant_id",
          "order_count",
          "gross_cents",
          "delivered_orders"
        ],
        "rowCount": 200,
        "orderedRowHash": "7af4e8467a90ace535a5b4a268338dfe66381d12d56241a38b9aa206c913448d",
        "unorderedRowHash": "9d9ed649f489433d7abc85bf610fbf962919aa4d2005b93e976ccb0bb6b51b46"
      }
    }
  ],
  "rv-dedup-rownumber": [
    {
      "id": "rv-dedup-rownumber-1f6z5ey",
      "skill": "rv-dedup-rownumber",
      "database": "rove",
      "task": "Deduplicate customers in city 2 with ROW_NUMBER over master_customer_id and keep rn = 1. Return columns: master_customer_id, customer_id, full_name. Order by: customer_id.",
      "starterSql": {
        "full": "SELECT\n  deduped.master_customer_id AS master_customer_id, deduped.customer_id AS customer_id, deduped.full_name AS full_name FROM (\n  SELECT\n    c.master_customer_id,\n    c.customer_id,\n    c.full_name,\n    ROW_NUMBER() OVER (PARTITION BY c.master_customer_id) AS rn\n  FROM customers c\n  WHERE c.signup_city_id = __BLANK_0__ AND c.is_deleted = false\n) deduped\nWHERE deduped.rn = 1 ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  deduped.master_customer_id AS master_customer_id, deduped.customer_id AS customer_id, deduped.full_name AS full_name FROM (\n  SELECT\n    c.master_customer_id,\n    c.customer_id,\n    c.full_name,\n    ROW_NUMBER() OVER (PARTITION BY c.master_customer_id) AS rn\n  FROM customers c\n  WHERE c.signup_city_id = 2 AND c.is_deleted = false\n) deduped\nWHERE deduped.rn = 1 ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "2",
          "__BLANK_1__": "customer_id"
        },
        "half": {
          "__BLANK_0__": "customer_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "deduped.master_customer_id AS master_customer_id, deduped.customer_id AS customer_id, deduped.full_name AS full_name",
          "__BLANK_1__": "(\n  SELECT\n    c.master_customer_id,\n    c.customer_id,\n    c.full_name,\n    ROW_NUMBER() OVER (PARTITION BY c.master_customer_id) AS rn\n  FROM customers c\n  WHERE c.signup_city_id = 2 AND c.is_deleted = false\n) deduped",
          "__BLANK_2__": "deduped.rn = 1",
          "__BLANK_3__": "customer_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "Use ROW_NUMBER() OVER (PARTITION BY master_customer_id), then keep rn = 1.",
      "expectedSql": "SELECT\n  deduped.master_customer_id AS master_customer_id, deduped.customer_id AS customer_id, deduped.full_name AS full_name FROM (\n  SELECT\n    c.master_customer_id,\n    c.customer_id,\n    c.full_name,\n    ROW_NUMBER() OVER (PARTITION BY c.master_customer_id) AS rn\n  FROM customers c\n  WHERE c.signup_city_id = 2 AND c.is_deleted = false\n) deduped\nWHERE deduped.rn = 1 ORDER BY customer_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "master_customer_id",
          "customer_id",
          "full_name"
        ],
        "rowCount": 200,
        "orderedRowHash": "2352cfa0a1c5e25d1bd0aeafa0c6ffdc19f319030d147d8934647774ecd96d95",
        "unorderedRowHash": "2352cfa0a1c5e25d1bd0aeafa0c6ffdc19f319030d147d8934647774ecd96d95"
      }
    }
  ],
  "rv-funnel-conversion": [
    {
      "id": "rv-funnel-conversion-lwa0km",
      "skill": "rv-funnel-conversion",
      "database": "rove",
      "task": "For city 10, count reached_customers at each funnel event_type from app_open to order_placed. Return columns: event_type, reached_customers. Order by: event_type.",
      "starterSql": {
        "full": "SELECT\n  e.event_type AS event_type, COUNT(DISTINCT e.customer_id) AS reached_customers FROM event_log e\nWHERE e.city_id = __BLANK_0__\n  AND e.event_type IN ('app_open', 'view_merchant', 'add_to_cart', 'checkout_start', 'order_placed')\nGROUP BY e.event_type ORDER BY __BLANK_1__",
        "half": "SELECT\n  e.event_type AS event_type, COUNT(DISTINCT e.customer_id) AS reached_customers FROM event_log e\nWHERE e.city_id = 10\n  AND e.event_type IN ('app_open', 'view_merchant', 'add_to_cart', 'checkout_start', 'order_placed')\nGROUP BY __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__\nGROUP BY __BLANK_3__ ORDER BY __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "10",
          "__BLANK_1__": "event_type"
        },
        "half": {
          "__BLANK_0__": "e.event_type",
          "__BLANK_1__": "event_type"
        },
        "blank": {
          "__BLANK_0__": "e.event_type AS event_type, COUNT(DISTINCT e.customer_id) AS reached_customers",
          "__BLANK_1__": "event_log e",
          "__BLANK_2__": "e.city_id = 10\n  AND e.event_type IN ('app_open', 'view_merchant', 'add_to_cart', 'checkout_start', 'order_placed')",
          "__BLANK_3__": "e.event_type",
          "__BLANK_4__": "event_type"
        }
      },
      "hint": "COUNT(DISTINCT customer_id) per event_type gives the funnel width at each step.",
      "expectedSql": "SELECT\n  e.event_type AS event_type, COUNT(DISTINCT e.customer_id) AS reached_customers FROM event_log e\nWHERE e.city_id = 10\n  AND e.event_type IN ('app_open', 'view_merchant', 'add_to_cart', 'checkout_start', 'order_placed')\nGROUP BY e.event_type ORDER BY event_type",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "event_type",
          "reached_customers"
        ],
        "rowCount": 5,
        "orderedRowHash": "1aec4d550d6982b30577688b9cbba2f0ce5616b8602c2013beb0de4e6ba60f20",
        "unorderedRowHash": "1aec4d550d6982b30577688b9cbba2f0ce5616b8602c2013beb0de4e6ba60f20"
      }
    }
  ],
  "rv-lag-lead-deltas": [
    {
      "id": "rv-lag-lead-deltas-mkrdbr",
      "skill": "rv-lag-lead-deltas",
      "database": "rove",
      "task": "For city 1 over a 30-day window, return order_id, placed_at, amount_cents, and amount_delta_cents. Return columns: order_id, city_id, placed_at, amount_cents, amount_delta_cents. Order by: city_id, order_id.",
      "starterSql": {
        "full": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.placed_at AS placed_at, o.amount_cents AS amount_cents, o.amount_cents - LAG(o.amount_cents) OVER (PARTITION BY o.city_id) AS amount_delta_cents FROM orders o\nWHERE o.city_id = __BLANK_0__\n  AND o.placed_at >= '2020-01-06T22:33:53.000Z'::timestamp\n  AND o.placed_at < '2020-01-06T22:33:53.000Z'::timestamp + INTERVAL '30 days' ORDER BY __BLANK_1__, __BLANK_2__ LIMIT 100",
        "half": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.placed_at AS placed_at, o.amount_cents AS amount_cents, o.amount_cents - LAG(o.amount_cents) OVER (PARTITION BY o.city_id) AS amount_delta_cents FROM orders o\nWHERE o.city_id = 1\n  AND o.placed_at >= '2020-01-06T22:33:53.000Z'::timestamp\n  AND o.placed_at < '2020-01-06T22:33:53.000Z'::timestamp + INTERVAL '30 days' ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "1",
          "__BLANK_1__": "city_id",
          "__BLANK_2__": "order_id"
        },
        "half": {
          "__BLANK_0__": "city_id, order_id",
          "__BLANK_1__": "100"
        },
        "blank": {
          "__BLANK_0__": "o.order_id AS order_id, o.city_id AS city_id, o.placed_at AS placed_at, o.amount_cents AS amount_cents, o.amount_cents - LAG(o.amount_cents) OVER (PARTITION BY o.city_id) AS amount_delta_cents",
          "__BLANK_1__": "orders o",
          "__BLANK_2__": "o.city_id = 1\n  AND o.placed_at >= '2020-01-06T22:33:53.000Z'::timestamp\n  AND o.placed_at < '2020-01-06T22:33:53.000Z'::timestamp + INTERVAL '30 days'",
          "__BLANK_3__": "city_id, order_id",
          "__BLANK_4__": "100"
        }
      },
      "hint": "LAG(amount_cents) pulls another row from the same city partition so the current row can subtract it.",
      "expectedSql": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.placed_at AS placed_at, o.amount_cents AS amount_cents, o.amount_cents - LAG(o.amount_cents) OVER (PARTITION BY o.city_id) AS amount_delta_cents FROM orders o\nWHERE o.city_id = 1\n  AND o.placed_at >= '2020-01-06T22:33:53.000Z'::timestamp\n  AND o.placed_at < '2020-01-06T22:33:53.000Z'::timestamp + INTERVAL '30 days' ORDER BY city_id, order_id LIMIT 100",
      "orderMatters": true,
      "rowCeiling": 100,
      "fingerprint": {
        "columns": [
          "order_id",
          "city_id",
          "placed_at",
          "amount_cents",
          "amount_delta_cents"
        ],
        "rowCount": 100,
        "orderedRowHash": "315d285d4ab87ed18e025015d7fc40d36c6ab127a7e1a48ee1cab372efe52371",
        "unorderedRowHash": "2f04dbd4b49a63255ce58b04b3de13f0355b14c09ead8c95f339ca5a8bc84d31"
      }
    }
  ],
  "rv-lifecycle-latency": [
    {
      "id": "rv-lifecycle-latency-19xehru",
      "skill": "rv-lifecycle-latency",
      "database": "rove",
      "task": "Report vehicle_type plus average apply-to-approve and approve-to-active seconds. Return columns: vehicle_type, avg_apply_to_approve_seconds, avg_approve_to_active_seconds. Order by: vehicle_type.",
      "starterSql": {
        "full": "SELECT\n  c.vehicle_type AS vehicle_type, ROUND(AVG(EXTRACT(EPOCH FROM c.approved_at - c.applied_at)), 2) AS avg_apply_to_approve_seconds, ROUND(AVG(EXTRACT(EPOCH FROM c.activated_at - c.approved_at)), 2) AS avg_approve_to_active_seconds FROM couriers c\nWHERE c.approved_at IS NOT NULL\n  AND c.activated_at IS NOT NULL\nGROUP BY c.vehicle_type ORDER BY __BLANK_0__ LIMIT 200",
        "half": "SELECT\n  c.vehicle_type AS vehicle_type, ROUND(AVG(EXTRACT(EPOCH FROM c.approved_at - c.applied_at)), 2) AS avg_apply_to_approve_seconds, ROUND(AVG(EXTRACT(EPOCH FROM c.activated_at - c.approved_at)), 2) AS avg_approve_to_active_seconds FROM couriers c\nWHERE c.approved_at IS NOT NULL\n  AND c.activated_at IS NOT NULL\nGROUP BY __BLANK_0__ ORDER BY __BLANK_1__ LIMIT __BLANK_2__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__\nGROUP BY __BLANK_3__ ORDER BY __BLANK_4__ LIMIT __BLANK_5__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "vehicle_type"
        },
        "half": {
          "__BLANK_0__": "c.vehicle_type",
          "__BLANK_1__": "vehicle_type",
          "__BLANK_2__": "200"
        },
        "blank": {
          "__BLANK_0__": "c.vehicle_type AS vehicle_type, ROUND(AVG(EXTRACT(EPOCH FROM c.approved_at - c.applied_at)), 2) AS avg_apply_to_approve_seconds, ROUND(AVG(EXTRACT(EPOCH FROM c.activated_at - c.approved_at)), 2) AS avg_approve_to_active_seconds",
          "__BLANK_1__": "couriers c",
          "__BLANK_2__": "c.approved_at IS NOT NULL\n  AND c.activated_at IS NOT NULL",
          "__BLANK_3__": "c.vehicle_type",
          "__BLANK_4__": "vehicle_type",
          "__BLANK_5__": "200"
        }
      },
      "hint": "Subtract timestamps, extract epoch seconds, filter NULL stamps, then average per vehicle_type.",
      "expectedSql": "SELECT\n  c.vehicle_type AS vehicle_type, ROUND(AVG(EXTRACT(EPOCH FROM c.approved_at - c.applied_at)), 2) AS avg_apply_to_approve_seconds, ROUND(AVG(EXTRACT(EPOCH FROM c.activated_at - c.approved_at)), 2) AS avg_approve_to_active_seconds FROM couriers c\nWHERE c.approved_at IS NOT NULL\n  AND c.activated_at IS NOT NULL\nGROUP BY c.vehicle_type ORDER BY vehicle_type LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "vehicle_type",
          "avg_apply_to_approve_seconds",
          "avg_approve_to_active_seconds"
        ],
        "rowCount": 139,
        "orderedRowHash": "e58af5bfbbda23c296c2057edcc13e8d7ef35682e0976c394e587bf78c80af6c",
        "unorderedRowHash": "cc1150f4df47a4da60ad8e6595d548e79be6c18096df4d63f288b091008b48e0"
      }
    }
  ],
  "rv-money-text-cast": [
    {
      "id": "rv-money-text-cast-1ffv1i0",
      "skill": "rv-money-text-cast",
      "database": "rove",
      "task": "Strip currency symbols from order_total_legacy in city 8 and cast the result to numeric. Return columns: order_id, legacy_dollars. Order by: order_id.",
      "starterSql": {
        "full": "SELECT\n  o.order_id AS order_id, REGEXP_REPLACE(o.order_total_legacy, '[^0-9.]', '', 'g')::numeric AS legacy_dollars FROM orders o\nWHERE o.city_id = __BLANK_0__\n  AND NULLIF(TRIM(COALESCE(o.order_total_legacy, '')), '') IS NOT NULL\n  AND o.order_total_legacy ~ '[0-9]' ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  o.order_id AS order_id, REGEXP_REPLACE(o.order_total_legacy, '[^0-9.]', '', 'g')::numeric AS legacy_dollars FROM orders o\nWHERE o.city_id = 8\n  AND NULLIF(TRIM(COALESCE(o.order_total_legacy, '')), '') IS NOT NULL\n  AND o.order_total_legacy ~ '[0-9]' ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "8",
          "__BLANK_1__": "order_id"
        },
        "half": {
          "__BLANK_0__": "order_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "o.order_id AS order_id, REGEXP_REPLACE(o.order_total_legacy, '[^0-9.]', '', 'g')::numeric AS legacy_dollars",
          "__BLANK_1__": "orders o",
          "__BLANK_2__": "o.city_id = 8\n  AND NULLIF(TRIM(COALESCE(o.order_total_legacy, '')), '') IS NOT NULL\n  AND o.order_total_legacy ~ '[0-9]'",
          "__BLANK_3__": "order_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "REGEXP_REPLACE(text, '[^0-9.]', '', 'g') keeps digits and decimal points before the cast.",
      "expectedSql": "SELECT\n  o.order_id AS order_id, REGEXP_REPLACE(o.order_total_legacy, '[^0-9.]', '', 'g')::numeric AS legacy_dollars FROM orders o\nWHERE o.city_id = 8\n  AND NULLIF(TRIM(COALESCE(o.order_total_legacy, '')), '') IS NOT NULL\n  AND o.order_total_legacy ~ '[0-9]' ORDER BY order_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "order_id",
          "legacy_dollars"
        ],
        "rowCount": 200,
        "orderedRowHash": "d76001236325dc91e6e856791978612e5f93aa424d757d688e85c93011bd1bb1",
        "unorderedRowHash": "d76001236325dc91e6e856791978612e5f93aa424d757d688e85c93011bd1bb1"
      }
    }
  ],
  "rv-moving-average-frame": [
    {
      "id": "rv-moving-average-frame-13pnvoe",
      "skill": "rv-moving-average-frame",
      "database": "rove",
      "task": "Compute a framed moving average over a gap-free date spine for city 1. Return columns: city_id, placed_at, order_day, gross_cents, trailing_7day_avg_cents. Order by: city_id, placed_at.",
      "starterSql": {
        "full": "SELECT\n  __BLANK_0__::smallint AS city_id, spine.order_day::timestamp AS placed_at, spine.order_day AS order_day, COALESCE(daily.gross_cents, 0) AS gross_cents, ROUND(AVG(COALESCE(daily.gross_cents, 0)) OVER (\n    RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n  ), 2) AS trailing_7day_avg_cents FROM generate_series('2020-02-07T01:05:36.000Z'::date, '2020-02-07T01:05:36.000Z'::date + INTERVAL '29 days', INTERVAL '1 day') AS spine(order_day)\nLEFT JOIN (\n  SELECT\n    o.placed_at::date AS order_day,\n    SUM(o.amount_cents) AS gross_cents\n  FROM orders o\n  WHERE o.city_id = __BLANK_1__\n    AND o.placed_at::date BETWEEN '2020-02-07T01:05:36.000Z'::date AND ('2020-02-07T01:05:36.000Z'::date + INTERVAL '29 days')\n  GROUP BY o.placed_at::date\n) daily ON daily.order_day = spine.order_day ORDER BY __BLANK_2__, __BLANK_3__",
        "half": "SELECT\n  1::smallint AS city_id, spine.order_day::timestamp AS placed_at, spine.order_day AS order_day, COALESCE(daily.gross_cents, 0) AS gross_cents, ROUND(AVG(COALESCE(daily.gross_cents, 0)) OVER (\n    RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n  ), 2) AS trailing_7day_avg_cents FROM generate_series('2020-02-07T01:05:36.000Z'::date, '2020-02-07T01:05:36.000Z'::date + INTERVAL '29 days', INTERVAL '1 day') AS spine(order_day)\nLEFT JOIN (\n  SELECT\n    o.placed_at::date AS order_day,\n    SUM(o.amount_cents) AS gross_cents\n  FROM orders o\n  WHERE o.city_id = 1\n    AND o.placed_at::date BETWEEN '2020-02-07T01:05:36.000Z'::date AND ('2020-02-07T01:05:36.000Z'::date + INTERVAL '29 days')\n  GROUP BY o.placed_at::date\n) daily ON daily.order_day = spine.order_day ORDER BY __BLANK_0__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "1",
          "__BLANK_1__": "1",
          "__BLANK_2__": "city_id",
          "__BLANK_3__": "placed_at"
        },
        "half": {
          "__BLANK_0__": "city_id, placed_at"
        },
        "blank": {
          "__BLANK_0__": "1::smallint AS city_id, spine.order_day::timestamp AS placed_at, spine.order_day AS order_day, COALESCE(daily.gross_cents, 0) AS gross_cents, ROUND(AVG(COALESCE(daily.gross_cents, 0)) OVER (\n    RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n  ), 2) AS trailing_7day_avg_cents",
          "__BLANK_1__": "generate_series('2020-02-07T01:05:36.000Z'::date, '2020-02-07T01:05:36.000Z'::date + INTERVAL '29 days', INTERVAL '1 day') AS spine(order_day)\nLEFT JOIN (\n  SELECT\n    o.placed_at::date AS order_day,\n    SUM(o.amount_cents) AS gross_cents\n  FROM orders o\n  WHERE o.city_id = 1\n    AND o.placed_at::date BETWEEN '2020-02-07T01:05:36.000Z'::date AND ('2020-02-07T01:05:36.000Z'::date + INTERVAL '29 days')\n  GROUP BY o.placed_at::date\n) daily ON daily.order_day = spine.order_day",
          "__BLANK_2__": "city_id, placed_at"
        }
      },
      "hint": "Use generate_series for the date spine, LEFT JOIN daily totals, then AVG over a RANGE BETWEEN frame.",
      "expectedSql": "SELECT\n  1::smallint AS city_id, spine.order_day::timestamp AS placed_at, spine.order_day AS order_day, COALESCE(daily.gross_cents, 0) AS gross_cents, ROUND(AVG(COALESCE(daily.gross_cents, 0)) OVER (\n    RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n  ), 2) AS trailing_7day_avg_cents FROM generate_series('2020-02-07T01:05:36.000Z'::date, '2020-02-07T01:05:36.000Z'::date + INTERVAL '29 days', INTERVAL '1 day') AS spine(order_day)\nLEFT JOIN (\n  SELECT\n    o.placed_at::date AS order_day,\n    SUM(o.amount_cents) AS gross_cents\n  FROM orders o\n  WHERE o.city_id = 1\n    AND o.placed_at::date BETWEEN '2020-02-07T01:05:36.000Z'::date AND ('2020-02-07T01:05:36.000Z'::date + INTERVAL '29 days')\n  GROUP BY o.placed_at::date\n) daily ON daily.order_day = spine.order_day ORDER BY city_id, placed_at",
      "orderMatters": true,
      "rowCeiling": 30,
      "fingerprint": {
        "columns": [
          "city_id",
          "placed_at",
          "order_day",
          "gross_cents",
          "trailing_7day_avg_cents"
        ],
        "rowCount": 30,
        "orderedRowHash": "57c100a0b1b23c2a51f017904d870bbf4de9ea44be1ca6190d454e007f4ff666",
        "unorderedRowHash": "57c100a0b1b23c2a51f017904d870bbf4de9ea44be1ca6190d454e007f4ff666"
      }
    }
  ],
  "rv-ntile-bucketing": [
    {
      "id": "rv-ntile-bucketing-1iv7dyh",
      "skill": "rv-ntile-bucketing",
      "database": "rove",
      "task": "For city 3, bucket bounded order rows into quartiles by average-order-value proxy fields. Return columns: order_id, city_id, merchant_id, amount_cents, aov_quartile. Order by: city_id, order_id.",
      "starterSql": {
        "full": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.merchant_id AS merchant_id, o.amount_cents AS amount_cents, NTILE(4) OVER (PARTITION BY o.city_id) AS aov_quartile FROM orders o\nWHERE o.city_id = __BLANK_0__ ORDER BY __BLANK_1__, __BLANK_2__ LIMIT 200",
        "half": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.merchant_id AS merchant_id, o.amount_cents AS amount_cents, NTILE(4) OVER (PARTITION BY o.city_id) AS aov_quartile FROM orders o\nWHERE o.city_id = 3 ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "3",
          "__BLANK_1__": "city_id",
          "__BLANK_2__": "order_id"
        },
        "half": {
          "__BLANK_0__": "city_id, order_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "o.order_id AS order_id, o.city_id AS city_id, o.merchant_id AS merchant_id, o.amount_cents AS amount_cents, NTILE(4) OVER (PARTITION BY o.city_id) AS aov_quartile",
          "__BLANK_1__": "orders o",
          "__BLANK_2__": "o.city_id = 3",
          "__BLANK_3__": "city_id, order_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "NTILE(4) OVER (PARTITION BY city_id) splits the bounded partition into four buckets.",
      "expectedSql": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.merchant_id AS merchant_id, o.amount_cents AS amount_cents, NTILE(4) OVER (PARTITION BY o.city_id) AS aov_quartile FROM orders o\nWHERE o.city_id = 3 ORDER BY city_id, order_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "order_id",
          "city_id",
          "merchant_id",
          "amount_cents",
          "aov_quartile"
        ],
        "rowCount": 200,
        "orderedRowHash": "75ca8c9af7fa62a9484c5aceafcf0f6aa18fc0360c8531abc9ff52acfe40e38b",
        "unorderedRowHash": "75ca8c9af7fa62a9484c5aceafcf0f6aa18fc0360c8531abc9ff52acfe40e38b"
      }
    }
  ],
  "rv-null-coalesce-nullif": [
    {
      "id": "rv-null-coalesce-nullif-h3gq2k",
      "skill": "rv-null-coalesce-nullif",
      "database": "rove",
      "task": "Fill missing tips with zero and turn blank legacy totals into NULL for city 8. Return columns: order_id, tip_cents_filled, legacy_total_or_null. Order by: order_id.",
      "starterSql": {
        "full": "SELECT\n  o.order_id AS order_id, COALESCE(o.tip_cents, 0) AS tip_cents_filled, NULLIF(TRIM(COALESCE(o.order_total_legacy, '')), '') AS legacy_total_or_null FROM orders o\nWHERE o.city_id = __BLANK_0__ ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  o.order_id AS order_id, COALESCE(o.tip_cents, 0) AS tip_cents_filled, NULLIF(TRIM(COALESCE(o.order_total_legacy, '')), '') AS legacy_total_or_null FROM orders o\nWHERE o.city_id = 8 ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "8",
          "__BLANK_1__": "order_id"
        },
        "half": {
          "__BLANK_0__": "order_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "o.order_id AS order_id, COALESCE(o.tip_cents, 0) AS tip_cents_filled, NULLIF(TRIM(COALESCE(o.order_total_legacy, '')), '') AS legacy_total_or_null",
          "__BLANK_1__": "orders o",
          "__BLANK_2__": "o.city_id = 8",
          "__BLANK_3__": "order_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "COALESCE fills a missing value; NULLIF turns an empty-string sentinel back into NULL.",
      "expectedSql": "SELECT\n  o.order_id AS order_id, COALESCE(o.tip_cents, 0) AS tip_cents_filled, NULLIF(TRIM(COALESCE(o.order_total_legacy, '')), '') AS legacy_total_or_null FROM orders o\nWHERE o.city_id = 8 ORDER BY order_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "order_id",
          "tip_cents_filled",
          "legacy_total_or_null"
        ],
        "rowCount": 200,
        "orderedRowHash": "fffda9ecfb6612968243d295e7bcbc5a66fbf39621646036d480719e7b9faafa",
        "unorderedRowHash": "fffda9ecfb6612968243d295e7bcbc5a66fbf39621646036d480719e7b9faafa"
      }
    }
  ],
  "rv-orphan-anti-join": [
    {
      "id": "rv-orphan-anti-join-1wla3ra",
      "skill": "rv-orphan-anti-join",
      "database": "rove",
      "task": "Find orphaned orders in city 2 with an anti-join against customers. Return columns: order_id, customer_id. Order by: order_id.",
      "starterSql": {
        "full": "SELECT\n  o.order_id AS order_id, o.customer_id AS customer_id FROM orders o\nWHERE o.city_id = __BLANK_0__\n  AND NOT EXISTS (SELECT 1 FROM customers c WHERE c.customer_id = o.customer_id) ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  o.order_id AS order_id, o.customer_id AS customer_id FROM orders o\nWHERE o.city_id = 2\n  AND NOT EXISTS (SELECT 1 FROM customers c WHERE c.customer_id = o.customer_id) ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "2",
          "__BLANK_1__": "order_id"
        },
        "half": {
          "__BLANK_0__": "order_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "o.order_id AS order_id, o.customer_id AS customer_id",
          "__BLANK_1__": "orders o",
          "__BLANK_2__": "o.city_id = 2\n  AND NOT EXISTS (SELECT 1 FROM customers c WHERE c.customer_id = o.customer_id)",
          "__BLANK_3__": "order_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "NOT EXISTS keeps only orders that fail to match a customer row.",
      "expectedSql": "SELECT\n  o.order_id AS order_id, o.customer_id AS customer_id FROM orders o\nWHERE o.city_id = 2\n  AND NOT EXISTS (SELECT 1 FROM customers c WHERE c.customer_id = o.customer_id) ORDER BY order_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "order_id",
          "customer_id"
        ],
        "rowCount": 200,
        "orderedRowHash": "6752fc2f100599007cc9ed13caad4a532c8612a94cbb3a3db996cecde208e685",
        "unorderedRowHash": "6752fc2f100599007cc9ed13caad4a532c8612a94cbb3a3db996cecde208e685"
      }
    }
  ],
  "rv-payment-dedup": [
    {
      "id": "rv-payment-dedup-yr7eps",
      "skill": "rv-payment-dedup",
      "database": "rove",
      "task": "Keep one payment per order and return order_id, payment_id, amount_cents. Return columns: order_id, payment_id, amount_cents. Order by: payment_id.",
      "starterSql": {
        "full": "SELECT\n  winner.order_id AS order_id, winner.payment_id AS payment_id, winner.amount_cents AS amount_cents FROM (\n  SELECT\n    p.order_id,\n    p.payment_id,\n    p.amount_cents,\n    MIN(p.payment_id) OVER (PARTITION BY p.order_id) AS chosen_payment_id\n  FROM payments p\n) winner\nWHERE winner.payment_id = winner.chosen_payment_id ORDER BY __BLANK_0__ LIMIT 200",
        "half": "SELECT\n  winner.order_id AS order_id, winner.payment_id AS payment_id, winner.amount_cents AS amount_cents FROM (\n  SELECT\n    p.order_id,\n    p.payment_id,\n    p.amount_cents,\n    MIN(p.payment_id) OVER (PARTITION BY p.order_id) AS chosen_payment_id\n  FROM payments p\n) winner\nWHERE winner.payment_id = winner.chosen_payment_id ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "payment_id"
        },
        "half": {
          "__BLANK_0__": "payment_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "winner.order_id AS order_id, winner.payment_id AS payment_id, winner.amount_cents AS amount_cents",
          "__BLANK_1__": "(\n  SELECT\n    p.order_id,\n    p.payment_id,\n    p.amount_cents,\n    MIN(p.payment_id) OVER (PARTITION BY p.order_id) AS chosen_payment_id\n  FROM payments p\n) winner",
          "__BLANK_2__": "winner.payment_id = winner.chosen_payment_id",
          "__BLANK_3__": "payment_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "Use a partitioned MIN(payment_id) to choose one deterministic representative payment per order.",
      "expectedSql": "SELECT\n  winner.order_id AS order_id, winner.payment_id AS payment_id, winner.amount_cents AS amount_cents FROM (\n  SELECT\n    p.order_id,\n    p.payment_id,\n    p.amount_cents,\n    MIN(p.payment_id) OVER (PARTITION BY p.order_id) AS chosen_payment_id\n  FROM payments p\n) winner\nWHERE winner.payment_id = winner.chosen_payment_id ORDER BY payment_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "order_id",
          "payment_id",
          "amount_cents"
        ],
        "rowCount": 200,
        "orderedRowHash": "94c57a34ac3ac889d1c11cc02c76ac541e4d99fc767b89a561518fabec18721e",
        "unorderedRowHash": "127d18be2b039c45f45ff17be8dca6ee8cbcee76f4b532c50616614c2521a094"
      }
    }
  ],
  "rv-profile-dirty-data": [
    {
      "id": "rv-profile-dirty-data-1itub1a",
      "skill": "rv-profile-dirty-data",
      "database": "rove",
      "task": "For each city, report city_id, table_name, total_rows, null_tips, and blank_totals for orders. Return columns: city_id, table_name, total_rows, null_tips, blank_totals. Order by: city_id.",
      "starterSql": {
        "full": "SELECT\n  o.city_id AS city_id, 'orders' AS table_name, COUNT(*) AS total_rows, COUNT(*) FILTER (WHERE o.tip_cents IS NULL) AS null_tips, COUNT(*) FILTER (WHERE TRIM(COALESCE(o.order_total_legacy, '')) = '') AS blank_totals FROM orders o\nGROUP BY o.city_id ORDER BY __BLANK_0__",
        "half": "SELECT\n  o.city_id AS city_id, 'orders' AS table_name, COUNT(*) AS total_rows, COUNT(*) FILTER (WHERE o.tip_cents IS NULL) AS null_tips, COUNT(*) FILTER (WHERE TRIM(COALESCE(o.order_total_legacy, '')) = '') AS blank_totals FROM orders o\nGROUP BY __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nGROUP BY __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "city_id"
        },
        "half": {
          "__BLANK_0__": "o.city_id",
          "__BLANK_1__": "city_id"
        },
        "blank": {
          "__BLANK_0__": "o.city_id AS city_id, 'orders' AS table_name, COUNT(*) AS total_rows, COUNT(*) FILTER (WHERE o.tip_cents IS NULL) AS null_tips, COUNT(*) FILTER (WHERE TRIM(COALESCE(o.order_total_legacy, '')) = '') AS blank_totals",
          "__BLANK_1__": "orders o",
          "__BLANK_2__": "o.city_id",
          "__BLANK_3__": "city_id"
        }
      },
      "hint": "Use COUNT(*) FILTER (WHERE ...) to count each dirty condition in one grouped scan.",
      "expectedSql": "SELECT\n  o.city_id AS city_id, 'orders' AS table_name, COUNT(*) AS total_rows, COUNT(*) FILTER (WHERE o.tip_cents IS NULL) AS null_tips, COUNT(*) FILTER (WHERE TRIM(COALESCE(o.order_total_legacy, '')) = '') AS blank_totals FROM orders o\nGROUP BY o.city_id ORDER BY city_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "city_id",
          "table_name",
          "total_rows",
          "null_tips",
          "blank_totals"
        ],
        "rowCount": 16,
        "orderedRowHash": "a23629a9e94e165667ba26db2f9e694b3f031fb05d806ac152f4c397b77a6933",
        "unorderedRowHash": "2f8f215c8f6b6d2d75820a82fee3d6ce7827fc4d205cc3bf65e6f501fc2ae0e3"
      }
    }
  ],
  "rv-rank-leaderboard": [
    {
      "id": "rv-rank-leaderboard-1d1t2yd",
      "skill": "rv-rank-leaderboard",
      "database": "rove",
      "task": "Build a courier leaderboard for city 3 using RANK over active couriers. Return columns: courier_id, home_city_id, lifetime_deliveries, delivery_rank. Order by: home_city_id, courier_id.",
      "starterSql": {
        "full": "SELECT\n  c.courier_id AS courier_id, c.home_city_id AS home_city_id, c.lifetime_deliveries AS lifetime_deliveries, RANK() OVER (PARTITION BY c.home_city_id) AS delivery_rank FROM couriers c\nWHERE c.home_city_id = __BLANK_0__ AND c.status = 'active' ORDER BY __BLANK_1__, __BLANK_2__ LIMIT 200",
        "half": "SELECT\n  c.courier_id AS courier_id, c.home_city_id AS home_city_id, c.lifetime_deliveries AS lifetime_deliveries, RANK() OVER (PARTITION BY c.home_city_id) AS delivery_rank FROM couriers c\nWHERE c.home_city_id = 3 AND c.status = 'active' ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "3",
          "__BLANK_1__": "home_city_id",
          "__BLANK_2__": "courier_id"
        },
        "half": {
          "__BLANK_0__": "home_city_id, courier_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "c.courier_id AS courier_id, c.home_city_id AS home_city_id, c.lifetime_deliveries AS lifetime_deliveries, RANK() OVER (PARTITION BY c.home_city_id) AS delivery_rank",
          "__BLANK_1__": "couriers c",
          "__BLANK_2__": "c.home_city_id = 3 AND c.status = 'active'",
          "__BLANK_3__": "home_city_id, courier_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "Use RANK() OVER (PARTITION BY home_city_id) and keep the result bounded to one city.",
      "expectedSql": "SELECT\n  c.courier_id AS courier_id, c.home_city_id AS home_city_id, c.lifetime_deliveries AS lifetime_deliveries, RANK() OVER (PARTITION BY c.home_city_id) AS delivery_rank FROM couriers c\nWHERE c.home_city_id = 3 AND c.status = 'active' ORDER BY home_city_id, courier_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "courier_id",
          "home_city_id",
          "lifetime_deliveries",
          "delivery_rank"
        ],
        "rowCount": 53,
        "orderedRowHash": "13a86529219a7addaf7cb17e8d68a1e3717da3321d987762aa4e253e01733c87",
        "unorderedRowHash": "13a86529219a7addaf7cb17e8d68a1e3717da3321d987762aa4e253e01733c87"
      }
    }
  ],
  "rv-rating-outlier-clean": [
    {
      "id": "rv-rating-outlier-clean-1ea9att",
      "skill": "rv-rating-outlier-clean",
      "database": "rove",
      "task": "Clean rating outliers in city 10, then average stars per courier_id. Return columns: courier_id, avg_stars, rating_count. Order by: courier_id.",
      "starterSql": {
        "full": "SELECT\n  r.courier_id AS courier_id, ROUND(AVG(r.stars), 2) AS avg_stars, COUNT(*) AS rating_count FROM ratings r\nJOIN orders o ON o.order_id = r.order_id\nWHERE o.city_id = __BLANK_0__ AND r.stars BETWEEN 1 AND 5 AND r.courier_id IS NOT NULL\nGROUP BY r.courier_id ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  r.courier_id AS courier_id, ROUND(AVG(r.stars), 2) AS avg_stars, COUNT(*) AS rating_count FROM ratings r\nJOIN orders o ON o.order_id = r.order_id\nWHERE o.city_id = 10 AND r.stars BETWEEN 1 AND 5 AND r.courier_id IS NOT NULL\nGROUP BY __BLANK_0__ ORDER BY __BLANK_1__ LIMIT __BLANK_2__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__\nGROUP BY __BLANK_3__ ORDER BY __BLANK_4__ LIMIT __BLANK_5__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "10",
          "__BLANK_1__": "courier_id"
        },
        "half": {
          "__BLANK_0__": "r.courier_id",
          "__BLANK_1__": "courier_id",
          "__BLANK_2__": "200"
        },
        "blank": {
          "__BLANK_0__": "r.courier_id AS courier_id, ROUND(AVG(r.stars), 2) AS avg_stars, COUNT(*) AS rating_count",
          "__BLANK_1__": "ratings r\nJOIN orders o ON o.order_id = r.order_id",
          "__BLANK_2__": "o.city_id = 10 AND r.stars BETWEEN 1 AND 5 AND r.courier_id IS NOT NULL",
          "__BLANK_3__": "r.courier_id",
          "__BLANK_4__": "courier_id",
          "__BLANK_5__": "200"
        }
      },
      "hint": "Filter stars BETWEEN 1 AND 5 before calculating AVG.",
      "expectedSql": "SELECT\n  r.courier_id AS courier_id, ROUND(AVG(r.stars), 2) AS avg_stars, COUNT(*) AS rating_count FROM ratings r\nJOIN orders o ON o.order_id = r.order_id\nWHERE o.city_id = 10 AND r.stars BETWEEN 1 AND 5 AND r.courier_id IS NOT NULL\nGROUP BY r.courier_id ORDER BY courier_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "courier_id",
          "avg_stars",
          "rating_count"
        ],
        "rowCount": 134,
        "orderedRowHash": "4e8f67fc54cb8711a2d1afb6e3faa852d8cf83ed1b964ab34ae1e966a5da76ae",
        "unorderedRowHash": "4e8f67fc54cb8711a2d1afb6e3faa852d8cf83ed1b964ab34ae1e966a5da76ae"
      }
    }
  ],
  "rv-recursive-cte": [
    {
      "id": "rv-recursive-cte-1bbcwgg",
      "skill": "rv-recursive-cte",
      "database": "rove",
      "task": "Walk the category tree from its cleaned root and return category_id, name, depth, and path. Return columns: category_id, name, depth, path. Order by: category_id.",
      "starterSql": {
        "full": "SELECT\n  tree_walk.category_id AS category_id, tree_walk.name AS name, tree_walk.depth AS depth, tree_walk.path AS path FROM (\n  WITH RECURSIVE cleaned AS (\n    SELECT\n      c.category_id,\n      c.name,\n      CASE\n        WHEN c.parent_category_id IN (SELECT __BLANK_0__ FROM categories) THEN c.parent_category_id\n        ELSE NULL\n      END AS parent_category_id\n    FROM categories c\n  ),\n  tree AS (\n    SELECT\n      cleaned.category_id,\n      cleaned.name,\n      1 AS depth,\n      cleaned.name AS path\n    FROM cleaned\n    WHERE cleaned.category_id = (SELECT MIN(__BLANK_1__) FROM cleaned WHERE parent_category_id IS NULL)\n    UNION ALL\n    SELECT\n      child.category_id,\n      child.name,\n      parent.depth + 1,\n      parent.path || ' > ' || child.name\n    FROM cleaned child\n    JOIN tree parent ON child.parent_category_id = parent.category_id\n  )\n  SELECT __BLANK_2__, name, depth, path\n  FROM tree\n) tree_walk ORDER BY __BLANK_3__",
        "half": "SELECT\n  tree_walk.category_id AS category_id, tree_walk.name AS name, tree_walk.depth AS depth, tree_walk.path AS path FROM (\n  WITH RECURSIVE cleaned AS (\n    SELECT\n      c.category_id,\n      c.name,\n      CASE\n        WHEN c.parent_category_id IN (SELECT category_id FROM categories) THEN c.parent_category_id\n        ELSE NULL\n      END AS parent_category_id\n    FROM categories c\n  ),\n  tree AS (\n    SELECT\n      cleaned.category_id,\n      cleaned.name,\n      1 AS depth,\n      cleaned.name AS path\n    FROM cleaned\n    WHERE cleaned.category_id = (SELECT MIN(category_id) FROM cleaned WHERE parent_category_id IS NULL)\n    UNION ALL\n    SELECT\n      child.category_id,\n      child.name,\n      parent.depth + 1,\n      parent.path || ' > ' || child.name\n    FROM cleaned child\n    JOIN tree parent ON child.parent_category_id = parent.category_id\n  )\n  SELECT category_id, name, depth, path\n  FROM tree\n) tree_walk ORDER BY __BLANK_0__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "category_id",
          "__BLANK_1__": "category_id",
          "__BLANK_2__": "category_id",
          "__BLANK_3__": "category_id"
        },
        "half": {
          "__BLANK_0__": "category_id"
        },
        "blank": {
          "__BLANK_0__": "tree_walk.category_id AS category_id, tree_walk.name AS name, tree_walk.depth AS depth, tree_walk.path AS path",
          "__BLANK_1__": "(\n  WITH RECURSIVE cleaned AS (\n    SELECT\n      c.category_id,\n      c.name,\n      CASE\n        WHEN c.parent_category_id IN (SELECT category_id FROM categories) THEN c.parent_category_id\n        ELSE NULL\n      END AS parent_category_id\n    FROM categories c\n  ),\n  tree AS (\n    SELECT\n      cleaned.category_id,\n      cleaned.name,\n      1 AS depth,\n      cleaned.name AS path\n    FROM cleaned\n    WHERE cleaned.category_id = (SELECT MIN(category_id) FROM cleaned WHERE parent_category_id IS NULL)\n    UNION ALL\n    SELECT\n      child.category_id,\n      child.name,\n      parent.depth + 1,\n      parent.path || ' > ' || child.name\n    FROM cleaned child\n    JOIN tree parent ON child.parent_category_id = parent.category_id\n  )\n  SELECT category_id, name, depth, path\n  FROM tree\n) tree_walk",
          "__BLANK_2__": "category_id"
        }
      },
      "hint": "Clean dangling parents first, then use WITH RECURSIVE: base root row, recursive child join, and path extension.",
      "expectedSql": "SELECT\n  tree_walk.category_id AS category_id, tree_walk.name AS name, tree_walk.depth AS depth, tree_walk.path AS path FROM (\n  WITH RECURSIVE cleaned AS (\n    SELECT\n      c.category_id,\n      c.name,\n      CASE\n        WHEN c.parent_category_id IN (SELECT category_id FROM categories) THEN c.parent_category_id\n        ELSE NULL\n      END AS parent_category_id\n    FROM categories c\n  ),\n  tree AS (\n    SELECT\n      cleaned.category_id,\n      cleaned.name,\n      1 AS depth,\n      cleaned.name AS path\n    FROM cleaned\n    WHERE cleaned.category_id = (SELECT MIN(category_id) FROM cleaned WHERE parent_category_id IS NULL)\n    UNION ALL\n    SELECT\n      child.category_id,\n      child.name,\n      parent.depth + 1,\n      parent.path || ' > ' || child.name\n    FROM cleaned child\n    JOIN tree parent ON child.parent_category_id = parent.category_id\n  )\n  SELECT category_id, name, depth, path\n  FROM tree\n) tree_walk ORDER BY category_id",
      "orderMatters": true,
      "rowCeiling": 60,
      "fingerprint": {
        "columns": [
          "category_id",
          "name",
          "depth",
          "path"
        ],
        "rowCount": 14,
        "orderedRowHash": "a9eddd8c8805f4ec38211e65529b351459789a28de54920aa36661939bea21cc",
        "unorderedRowHash": "08d544a8623970b760c065e6c3f7eee2679cfcc3238f50259e8053f83cbeda10"
      }
    }
  ],
  "rv-regex-clean-contacts": [
    {
      "id": "rv-regex-clean-contacts-b3pp2r",
      "skill": "rv-regex-clean-contacts",
      "database": "rove",
      "task": "For signup city 15, return customer_id, phone_digits, and clean_email. Return columns: customer_id, phone_digits, clean_email. Order by: customer_id.",
      "starterSql": {
        "full": "SELECT\n  c.customer_id AS customer_id, REGEXP_REPLACE(c.phone, '[^0-9]', '', 'g') AS phone_digits, LOWER(TRIM(REGEXP_REPLACE(c.email, '^mailto:', ''))) AS clean_email FROM customers c\nWHERE c.signup_city_id = __BLANK_0__ AND c.phone IS NOT NULL ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  c.customer_id AS customer_id, REGEXP_REPLACE(c.phone, '[^0-9]', '', 'g') AS phone_digits, LOWER(TRIM(REGEXP_REPLACE(c.email, '^mailto:', ''))) AS clean_email FROM customers c\nWHERE c.signup_city_id = 15 AND c.phone IS NOT NULL ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "15",
          "__BLANK_1__": "customer_id"
        },
        "half": {
          "__BLANK_0__": "customer_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "c.customer_id AS customer_id, REGEXP_REPLACE(c.phone, '[^0-9]', '', 'g') AS phone_digits, LOWER(TRIM(REGEXP_REPLACE(c.email, '^mailto:', ''))) AS clean_email",
          "__BLANK_1__": "customers c",
          "__BLANK_2__": "c.signup_city_id = 15 AND c.phone IS NOT NULL",
          "__BLANK_3__": "customer_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "REGEXP_REPLACE(phone, '[^0-9]', '', 'g') keeps only digits; strip a leading mailto: from email.",
      "expectedSql": "SELECT\n  c.customer_id AS customer_id, REGEXP_REPLACE(c.phone, '[^0-9]', '', 'g') AS phone_digits, LOWER(TRIM(REGEXP_REPLACE(c.email, '^mailto:', ''))) AS clean_email FROM customers c\nWHERE c.signup_city_id = 15 AND c.phone IS NOT NULL ORDER BY customer_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "customer_id",
          "phone_digits",
          "clean_email"
        ],
        "rowCount": 96,
        "orderedRowHash": "78ad9be47749e7ce061bd34ba87c83241d0732a0aa117927de1aaf24ecac1bf5",
        "unorderedRowHash": "78ad9be47749e7ce061bd34ba87c83241d0732a0aa117927de1aaf24ecac1bf5"
      }
    }
  ],
  "rv-retention-cohort": [
    {
      "id": "rv-retention-cohort-1vgvwhq",
      "skill": "rv-retention-cohort",
      "database": "rove",
      "task": "Build a retention cohort rollup for city 5: signup_ts month and active_customers. Return columns: signup_ts, active_customers. Order by: signup_ts.",
      "starterSql": {
        "full": "SELECT\n  date_trunc('month', c.signup_ts)::date AS signup_ts, COUNT(DISTINCT c.customer_id) AS active_customers FROM customers c\nJOIN orders o ON o.customer_id = c.customer_id\nWHERE c.signup_city_id = __BLANK_0__ AND c.is_deleted = false\nGROUP BY date_trunc('month', c.signup_ts) ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  date_trunc('month', c.signup_ts)::date AS signup_ts, COUNT(DISTINCT c.customer_id) AS active_customers FROM customers c\nJOIN orders o ON o.customer_id = c.customer_id\nWHERE c.signup_city_id = 5 AND c.is_deleted = false\nGROUP BY __BLANK_0__ ORDER BY __BLANK_1__ LIMIT __BLANK_2__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__\nGROUP BY __BLANK_3__ ORDER BY __BLANK_4__ LIMIT __BLANK_5__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "5",
          "__BLANK_1__": "signup_ts"
        },
        "half": {
          "__BLANK_0__": "date_trunc('month', c.signup_ts)",
          "__BLANK_1__": "signup_ts",
          "__BLANK_2__": "200"
        },
        "blank": {
          "__BLANK_0__": "date_trunc('month', c.signup_ts)::date AS signup_ts, COUNT(DISTINCT c.customer_id) AS active_customers",
          "__BLANK_1__": "customers c\nJOIN orders o ON o.customer_id = c.customer_id",
          "__BLANK_2__": "c.signup_city_id = 5 AND c.is_deleted = false",
          "__BLANK_3__": "date_trunc('month', c.signup_ts)",
          "__BLANK_4__": "signup_ts",
          "__BLANK_5__": "200"
        }
      },
      "hint": "date_trunc('month', signup_ts) is the cohort month; date_trunc('month', placed_at) is the activity month.",
      "expectedSql": "SELECT\n  date_trunc('month', c.signup_ts)::date AS signup_ts, COUNT(DISTINCT c.customer_id) AS active_customers FROM customers c\nJOIN orders o ON o.customer_id = c.customer_id\nWHERE c.signup_city_id = 5 AND c.is_deleted = false\nGROUP BY date_trunc('month', c.signup_ts) ORDER BY signup_ts LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 150,
      "fingerprint": {
        "columns": [
          "signup_ts",
          "active_customers"
        ],
        "rowCount": 24,
        "orderedRowHash": "fe07f0c6897f5f420bb6b545037070ed7736db1581fcff37a69fcabee9fe46f2",
        "unorderedRowHash": "fe07f0c6897f5f420bb6b545037070ed7736db1581fcff37a69fcabee9fe46f2"
      }
    }
  ],
  "rv-running-total": [
    {
      "id": "rv-running-total-vdwqk",
      "skill": "rv-running-total",
      "database": "rove",
      "task": "Add a city-level running_gross_cents window value to the bounded order rows for city 1. Return columns: order_id, city_id, placed_at, amount_cents, running_gross_cents. Order by: city_id, order_id.",
      "starterSql": {
        "full": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.placed_at AS placed_at, o.amount_cents AS amount_cents, SUM(o.amount_cents) OVER (PARTITION BY o.city_id) AS running_gross_cents FROM orders o\nWHERE o.city_id = __BLANK_0__\n  AND o.placed_at >= '2020-02-01T14:21:46.000Z'::timestamp\n  AND o.placed_at < '2020-02-01T14:21:46.000Z'::timestamp + INTERVAL '30 days' ORDER BY __BLANK_1__, __BLANK_2__ LIMIT 100",
        "half": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.placed_at AS placed_at, o.amount_cents AS amount_cents, SUM(o.amount_cents) OVER (PARTITION BY o.city_id) AS running_gross_cents FROM orders o\nWHERE o.city_id = 1\n  AND o.placed_at >= '2020-02-01T14:21:46.000Z'::timestamp\n  AND o.placed_at < '2020-02-01T14:21:46.000Z'::timestamp + INTERVAL '30 days' ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "1",
          "__BLANK_1__": "city_id",
          "__BLANK_2__": "order_id"
        },
        "half": {
          "__BLANK_0__": "city_id, order_id",
          "__BLANK_1__": "100"
        },
        "blank": {
          "__BLANK_0__": "o.order_id AS order_id, o.city_id AS city_id, o.placed_at AS placed_at, o.amount_cents AS amount_cents, SUM(o.amount_cents) OVER (PARTITION BY o.city_id) AS running_gross_cents",
          "__BLANK_1__": "orders o",
          "__BLANK_2__": "o.city_id = 1\n  AND o.placed_at >= '2020-02-01T14:21:46.000Z'::timestamp\n  AND o.placed_at < '2020-02-01T14:21:46.000Z'::timestamp + INTERVAL '30 days'",
          "__BLANK_3__": "city_id, order_id",
          "__BLANK_4__": "100"
        }
      },
      "hint": "SUM(amount_cents) OVER (PARTITION BY city_id) keeps row detail while adding a city-level total.",
      "expectedSql": "SELECT\n  o.order_id AS order_id, o.city_id AS city_id, o.placed_at AS placed_at, o.amount_cents AS amount_cents, SUM(o.amount_cents) OVER (PARTITION BY o.city_id) AS running_gross_cents FROM orders o\nWHERE o.city_id = 1\n  AND o.placed_at >= '2020-02-01T14:21:46.000Z'::timestamp\n  AND o.placed_at < '2020-02-01T14:21:46.000Z'::timestamp + INTERVAL '30 days' ORDER BY city_id, order_id LIMIT 100",
      "orderMatters": true,
      "rowCeiling": 100,
      "fingerprint": {
        "columns": [
          "order_id",
          "city_id",
          "placed_at",
          "amount_cents",
          "running_gross_cents"
        ],
        "rowCount": 100,
        "orderedRowHash": "040dadace931b19b7c8bf6260141997e5fab50d840d43aeb542017aadab6aee4",
        "unorderedRowHash": "9a45dbee363451372bb4256997917560ff06023750a0ae5a9b582450de11cdff"
      }
    }
  ],
  "rv-sessionization": [
    {
      "id": "rv-sessionization-1x1n91o",
      "skill": "rv-sessionization",
      "database": "rove",
      "task": "Sessionize events in city 1; return session_id, customer_id, session_seq, session_start, session_end, event_count. Return columns: session_id, customer_id, session_seq, session_start, session_end, event_count. Order by: session_id.",
      "starterSql": {
        "full": "SELECT\n  sessioned.session_id AS session_id, sessioned.customer_id AS customer_id, sessioned.session_seq AS session_seq, MIN(sessioned.event_ts) AS session_start, MAX(sessioned.event_ts) AS session_end, COUNT(*) AS event_count FROM (\n  SELECT\n    flagged.session_id,\n    flagged.customer_id,\n    flagged.event_ts,\n    SUM(flagged.is_new_session) OVER (PARTITION BY flagged.customer_id, flagged.session_id) AS session_seq\n  FROM (\n    SELECT\n      e.session_id,\n      e.customer_id,\n      e.event_ts,\n      CASE\n        WHEN LAG(e.event_ts) OVER (PARTITION BY e.customer_id, e.session_id) IS NULL\n          OR e.event_ts - LAG(e.event_ts) OVER (PARTITION BY e.customer_id, e.session_id) > INTERVAL '30 minutes'\n        THEN __BLANK_0__ ELSE 0\n      END AS is_new_session\n    FROM event_log e\n    WHERE e.city_id = __BLANK_1__\n  ) flagged\n) sessioned\nGROUP BY sessioned.session_id, sessioned.customer_id, sessioned.session_seq ORDER BY __BLANK_2__ LIMIT 100",
        "half": "SELECT\n  sessioned.session_id AS session_id, sessioned.customer_id AS customer_id, sessioned.session_seq AS session_seq, MIN(sessioned.event_ts) AS session_start, MAX(sessioned.event_ts) AS session_end, COUNT(*) AS event_count FROM (\n  SELECT\n    flagged.session_id,\n    flagged.customer_id,\n    flagged.event_ts,\n    SUM(flagged.is_new_session) OVER (PARTITION BY flagged.customer_id, flagged.session_id) AS session_seq\n  FROM (\n    SELECT\n      e.session_id,\n      e.customer_id,\n      e.event_ts,\n      CASE\n        WHEN LAG(e.event_ts) OVER (PARTITION BY e.customer_id, e.session_id) IS NULL\n          OR e.event_ts - LAG(e.event_ts) OVER (PARTITION BY e.customer_id, e.session_id) > INTERVAL '30 minutes'\n        THEN 1 ELSE 0\n      END AS is_new_session\n    FROM event_log e\n    WHERE e.city_id = 1\n  ) flagged\n) sessioned\nGROUP BY sessioned.session_id, sessioned.customer_id, sessioned.session_seq ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nGROUP BY __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "1",
          "__BLANK_1__": "1",
          "__BLANK_2__": "session_id"
        },
        "half": {
          "__BLANK_0__": "session_id",
          "__BLANK_1__": "100"
        },
        "blank": {
          "__BLANK_0__": "sessioned.session_id AS session_id, sessioned.customer_id AS customer_id, sessioned.session_seq AS session_seq, MIN(sessioned.event_ts) AS session_start, MAX(sessioned.event_ts) AS session_end, COUNT(*) AS event_count",
          "__BLANK_1__": "(\n  SELECT\n    flagged.session_id,\n    flagged.customer_id,\n    flagged.event_ts,\n    SUM(flagged.is_new_session) OVER (PARTITION BY flagged.customer_id, flagged.session_id) AS session_seq\n  FROM (\n    SELECT\n      e.session_id,\n      e.customer_id,\n      e.event_ts,\n      CASE\n        WHEN LAG(e.event_ts) OVER (PARTITION BY e.customer_id, e.session_id) IS NULL\n          OR e.event_ts - LAG(e.event_ts) OVER (PARTITION BY e.customer_id, e.session_id) > INTERVAL '30 minutes'\n        THEN 1 ELSE 0\n      END AS is_new_session\n    FROM event_log e\n    WHERE e.city_id = 1\n  ) flagged\n) sessioned",
          "__BLANK_2__": "sessioned.session_id, sessioned.customer_id, sessioned.session_seq",
          "__BLANK_3__": "session_id",
          "__BLANK_4__": "100"
        }
      },
      "hint": "Flag a new session when LAG(event_ts) is NULL or the gap exceeds INTERVAL '30 minutes', then sum the flags into session_seq.",
      "expectedSql": "SELECT\n  sessioned.session_id AS session_id, sessioned.customer_id AS customer_id, sessioned.session_seq AS session_seq, MIN(sessioned.event_ts) AS session_start, MAX(sessioned.event_ts) AS session_end, COUNT(*) AS event_count FROM (\n  SELECT\n    flagged.session_id,\n    flagged.customer_id,\n    flagged.event_ts,\n    SUM(flagged.is_new_session) OVER (PARTITION BY flagged.customer_id, flagged.session_id) AS session_seq\n  FROM (\n    SELECT\n      e.session_id,\n      e.customer_id,\n      e.event_ts,\n      CASE\n        WHEN LAG(e.event_ts) OVER (PARTITION BY e.customer_id, e.session_id) IS NULL\n          OR e.event_ts - LAG(e.event_ts) OVER (PARTITION BY e.customer_id, e.session_id) > INTERVAL '30 minutes'\n        THEN 1 ELSE 0\n      END AS is_new_session\n    FROM event_log e\n    WHERE e.city_id = 1\n  ) flagged\n) sessioned\nGROUP BY sessioned.session_id, sessioned.customer_id, sessioned.session_seq ORDER BY session_id LIMIT 100",
      "orderMatters": true,
      "rowCeiling": 100,
      "fingerprint": {
        "columns": [
          "session_id",
          "customer_id",
          "session_seq",
          "session_start",
          "session_end",
          "event_count"
        ],
        "rowCount": 100,
        "orderedRowHash": "66cd73f982217df9aa6d58444dd4918a9b0c646d0ccaa526f901c8ae4e09a65f",
        "unorderedRowHash": "66cd73f982217df9aa6d58444dd4918a9b0c646d0ccaa526f901c8ae4e09a65f"
      }
    }
  ],
  "rv-soft-delete-valid": [
    {
      "id": "rv-soft-delete-valid-nlo1r0",
      "skill": "rv-soft-delete-valid",
      "database": "rove",
      "task": "For city 2, count valid_tickets per support ticket category, excluding soft-deleted tickets. Return columns: category, valid_tickets. Order by: category.",
      "starterSql": {
        "full": "SELECT\n  t.category AS category, COUNT(*) AS valid_tickets FROM support_tickets t\nJOIN orders o ON o.order_id = t.order_id\nWHERE o.city_id = __BLANK_0__ AND t.is_deleted = false\nGROUP BY t.category ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  t.category AS category, COUNT(*) AS valid_tickets FROM support_tickets t\nJOIN orders o ON o.order_id = t.order_id\nWHERE o.city_id = 2 AND t.is_deleted = false\nGROUP BY __BLANK_0__ ORDER BY __BLANK_1__ LIMIT __BLANK_2__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__\nGROUP BY __BLANK_3__ ORDER BY __BLANK_4__ LIMIT __BLANK_5__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "2",
          "__BLANK_1__": "category"
        },
        "half": {
          "__BLANK_0__": "t.category",
          "__BLANK_1__": "category",
          "__BLANK_2__": "200"
        },
        "blank": {
          "__BLANK_0__": "t.category AS category, COUNT(*) AS valid_tickets",
          "__BLANK_1__": "support_tickets t\nJOIN orders o ON o.order_id = t.order_id",
          "__BLANK_2__": "o.city_id = 2 AND t.is_deleted = false",
          "__BLANK_3__": "t.category",
          "__BLANK_4__": "category",
          "__BLANK_5__": "200"
        }
      },
      "hint": "Soft-deleted tickets still exist; filter t.is_deleted = false before counting. LIMIT bounds noisy category variants.",
      "expectedSql": "SELECT\n  t.category AS category, COUNT(*) AS valid_tickets FROM support_tickets t\nJOIN orders o ON o.order_id = t.order_id\nWHERE o.city_id = 2 AND t.is_deleted = false\nGROUP BY t.category ORDER BY category LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "category",
          "valid_tickets"
        ],
        "rowCount": 173,
        "orderedRowHash": "17e762a3a54098f921af84ec1e876461f499a88fd55a0110b9e11ea5c875c068",
        "unorderedRowHash": "4fa2eed697399a526016385ef4b3d5bdc9b04d6ca2766ba01bbb078f3cf859d2"
      }
    }
  ],
  "rv-text-normalize": [
    {
      "id": "rv-text-normalize-19g55jz",
      "skill": "rv-text-normalize",
      "database": "rove",
      "task": "For signup city 2, return customer_id and clean_name as the trimmed, lowercased full_name. Return columns: customer_id, clean_name. Order by: customer_id.",
      "starterSql": {
        "full": "SELECT\n  c.customer_id AS customer_id, LOWER(TRIM(c.full_name)) AS clean_name FROM customers c\nWHERE c.signup_city_id = __BLANK_0__ AND c.full_name IS NOT NULL ORDER BY __BLANK_1__ LIMIT 200",
        "half": "SELECT\n  c.customer_id AS customer_id, LOWER(TRIM(c.full_name)) AS clean_name FROM customers c\nWHERE c.signup_city_id = 2 AND c.full_name IS NOT NULL ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "2",
          "__BLANK_1__": "customer_id"
        },
        "half": {
          "__BLANK_0__": "customer_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "c.customer_id AS customer_id, LOWER(TRIM(c.full_name)) AS clean_name",
          "__BLANK_1__": "customers c",
          "__BLANK_2__": "c.signup_city_id = 2 AND c.full_name IS NOT NULL",
          "__BLANK_3__": "customer_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "LOWER(TRIM(full_name)) collapses casing and whitespace variants.",
      "expectedSql": "SELECT\n  c.customer_id AS customer_id, LOWER(TRIM(c.full_name)) AS clean_name FROM customers c\nWHERE c.signup_city_id = 2 AND c.full_name IS NOT NULL ORDER BY customer_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "customer_id",
          "clean_name"
        ],
        "rowCount": 200,
        "orderedRowHash": "7aacb18305e1ce086d1f7fed86cd9666a271392129704f0cb88ede162de87816",
        "unorderedRowHash": "7aacb18305e1ce086d1f7fed86cd9666a271392129704f0cb88ede162de87816"
      }
    }
  ],
  "rv-timezone-city-join": [
    {
      "id": "rv-timezone-city-join-9sgjc9",
      "skill": "rv-timezone-city-join",
      "database": "rove",
      "task": "Join city timezone data for every city and convert placed_at with AT TIME ZONE. Return columns: city_id, city_name, iana_timezone, earliest_utc_instant, orders_placed. Order by: city_id.",
      "starterSql": {
        "full": "SELECT\n  o.city_id AS city_id, ci.name AS city_name, ci.timezone AS iana_timezone, MIN(o.placed_at AT TIME ZONE ci.timezone) AS earliest_utc_instant, COUNT(*) AS orders_placed FROM orders o\nJOIN cities ci ON ci.city_id = o.city_id\nGROUP BY o.city_id, ci.name, ci.timezone ORDER BY __BLANK_0__",
        "half": "SELECT\n  o.city_id AS city_id, ci.name AS city_name, ci.timezone AS iana_timezone, MIN(o.placed_at AT TIME ZONE ci.timezone) AS earliest_utc_instant, COUNT(*) AS orders_placed FROM orders o\nJOIN cities ci ON ci.city_id = o.city_id\nGROUP BY __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nGROUP BY __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "city_id"
        },
        "half": {
          "__BLANK_0__": "o.city_id, ci.name, ci.timezone",
          "__BLANK_1__": "city_id"
        },
        "blank": {
          "__BLANK_0__": "o.city_id AS city_id, ci.name AS city_name, ci.timezone AS iana_timezone, MIN(o.placed_at AT TIME ZONE ci.timezone) AS earliest_utc_instant, COUNT(*) AS orders_placed",
          "__BLANK_1__": "orders o\nJOIN cities ci ON ci.city_id = o.city_id",
          "__BLANK_2__": "o.city_id, ci.name, ci.timezone",
          "__BLANK_3__": "city_id"
        }
      },
      "hint": "Join cities to read timezone, then convert placed_at with AT TIME ZONE; do not trust the offset column.",
      "expectedSql": "SELECT\n  o.city_id AS city_id, ci.name AS city_name, ci.timezone AS iana_timezone, MIN(o.placed_at AT TIME ZONE ci.timezone) AS earliest_utc_instant, COUNT(*) AS orders_placed FROM orders o\nJOIN cities ci ON ci.city_id = o.city_id\nGROUP BY o.city_id, ci.name, ci.timezone ORDER BY city_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "city_id",
          "city_name",
          "iana_timezone",
          "earliest_utc_instant",
          "orders_placed"
        ],
        "rowCount": 16,
        "orderedRowHash": "cec8a1b7789b2bbacf2c1d0a4ad322f446510ad8e4b33fe3fd772fcf505ab044",
        "unorderedRowHash": "7f0efda387a8a95d9ea763650803ccb860f42c89ae5a06d3941e9f9c2dc387df"
      }
    }
  ],
  "rv-topn-per-group": [
    {
      "id": "rv-topn-per-group-5b7a0f",
      "skill": "rv-topn-per-group",
      "database": "rove",
      "task": "For city 3, return three merchant rows with city_id, merchant_id, and order_count. Return columns: city_id, merchant_id, order_count. Order by: city_id, merchant_id.",
      "starterSql": {
        "full": "SELECT\n  top3.city_id AS city_id, top3.merchant_id AS merchant_id, top3.order_count AS order_count FROM (\n  SELECT\n    o.city_id,\n    o.merchant_id,\n    COUNT(*) AS order_count,\n    ROW_NUMBER() OVER (PARTITION BY o.city_id) AS rn\n  FROM orders o\n  WHERE o.city_id = __BLANK_0__\n  GROUP BY o.city_id, o.merchant_id\n) top3\nWHERE top3.rn <= __BLANK_1__ ORDER BY __BLANK_2__, __BLANK_3__ LIMIT 200",
        "half": "SELECT\n  top3.city_id AS city_id, top3.merchant_id AS merchant_id, top3.order_count AS order_count FROM (\n  SELECT\n    o.city_id,\n    o.merchant_id,\n    COUNT(*) AS order_count,\n    ROW_NUMBER() OVER (PARTITION BY o.city_id) AS rn\n  FROM orders o\n  WHERE o.city_id = 3\n  GROUP BY o.city_id, o.merchant_id\n) top3\nWHERE top3.rn <= 3 ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT\n  __BLANK_0__ FROM __BLANK_1__\nWHERE __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "3",
          "__BLANK_1__": "3",
          "__BLANK_2__": "city_id",
          "__BLANK_3__": "merchant_id"
        },
        "half": {
          "__BLANK_0__": "city_id, merchant_id",
          "__BLANK_1__": "200"
        },
        "blank": {
          "__BLANK_0__": "top3.city_id AS city_id, top3.merchant_id AS merchant_id, top3.order_count AS order_count",
          "__BLANK_1__": "(\n  SELECT\n    o.city_id,\n    o.merchant_id,\n    COUNT(*) AS order_count,\n    ROW_NUMBER() OVER (PARTITION BY o.city_id) AS rn\n  FROM orders o\n  WHERE o.city_id = 3\n  GROUP BY o.city_id, o.merchant_id\n) top3",
          "__BLANK_2__": "top3.rn <= 3",
          "__BLANK_3__": "city_id, merchant_id",
          "__BLANK_4__": "200"
        }
      },
      "hint": "Aggregate by city_id and merchant_id, add ROW_NUMBER() OVER (PARTITION BY city_id), then keep rn <= 3.",
      "expectedSql": "SELECT\n  top3.city_id AS city_id, top3.merchant_id AS merchant_id, top3.order_count AS order_count FROM (\n  SELECT\n    o.city_id,\n    o.merchant_id,\n    COUNT(*) AS order_count,\n    ROW_NUMBER() OVER (PARTITION BY o.city_id) AS rn\n  FROM orders o\n  WHERE o.city_id = 3\n  GROUP BY o.city_id, o.merchant_id\n) top3\nWHERE top3.rn <= 3 ORDER BY city_id, merchant_id LIMIT 200",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "city_id",
          "merchant_id",
          "order_count"
        ],
        "rowCount": 3,
        "orderedRowHash": "37a904467b307dd03eb126a3995504712bd6a4e8ddd53d518ebd1b7b8dc69055",
        "unorderedRowHash": "37a904467b307dd03eb126a3995504712bd6a4e8ddd53d518ebd1b7b8dc69055"
      }
    }
  ]
};
