import type { Fingerprint } from '../fingerprint';

// Generated by scripts/validate-interview.ts. Do not edit by hand.
// Maps an interview problem id to the result fingerprint baked from its expectedSql.
export const INTERVIEW_FINGERPRINTS: Record<string, Fingerprint> = {
  "iv-ap-habitable-shortlist-1": {
    "columns": [
      "planet_name",
      "planet_type"
    ],
    "rowCount": 28,
    "orderedRowHash": "52b3b1d371781c06eccf9ba6060b0ae5371ff423f8668d71eddde58a286be9f3",
    "unorderedRowHash": "52b3b1d371781c06eccf9ba6060b0ae5371ff423f8668d71eddde58a286be9f3"
  },
  "iv-ap-nearby-hosts-1": {
    "columns": [
      "star_name",
      "spectral_type",
      "distance_ly"
    ],
    "rowCount": 21,
    "orderedRowHash": "9c9b6865f3d86c0c524e2c5144c5261b5e173d0d916247e55ce06ca027397611",
    "unorderedRowHash": "9859e09e2b7e23ab7f82a6041154628089da9cc36b59a035927bc68c75d98126"
  },
  "iv-ap-recent-discoveries-1": {
    "columns": [
      "planet_name",
      "discovery_year",
      "discovery_method"
    ],
    "rowCount": 18,
    "orderedRowHash": "d3a273f49d2fbb96361d5713439ad9f9caae6d1136af3f6a9594cbf0d7ec1958",
    "unorderedRowHash": "fc81dba8b8ecf28f61e10310dab5efbbcaaf763d87ce79457c278ed9f524e2d5"
  },
  "iv-ap-gas-giant-count-1": {
    "columns": [
      "gas_giant_count"
    ],
    "rowCount": 1,
    "orderedRowHash": "85e7f7aa69715db2a19a30bc27f37f9fe60cbebf9b0d8f520d52eb05a69bd576",
    "unorderedRowHash": "85e7f7aa69715db2a19a30bc27f37f9fe60cbebf9b0d8f520d52eb05a69bd576"
  },
  "iv-ap-method-share-1": {
    "columns": [
      "discovery_method",
      "planet_count"
    ],
    "rowCount": 5,
    "orderedRowHash": "56fb6999c210e2c8809d733187bb507040a3f0f92f33660a9b1fede6ff12093a",
    "unorderedRowHash": "124b6aca2a9c268d466f35cfef5deb22b77af232f2bd6cd5c22869649cb98480"
  },
  "iv-ap-avg-temp-by-type-1": {
    "columns": [
      "planet_type",
      "avg_temp_k"
    ],
    "rowCount": 4,
    "orderedRowHash": "9feac29bfbe6fa22adb839aa0c1e60944b24517c4b21fb6255b374f742d6d5a9",
    "unorderedRowHash": "8a6f14e9f68628984e1fe938eeecbde51ce428d322c4b4a8f00b2df517a07636"
  },
  "iv-ap-prolific-facilities-1": {
    "columns": [
      "facility_name",
      "planet_count"
    ],
    "rowCount": 5,
    "orderedRowHash": "180c6cf4bd054de636178ae946724d9a5410b7aac76272bdf4c451a4667f5212",
    "unorderedRowHash": "2187238064f6cce579d16867b91ceb8fb0f97c887e309122d32ee150308730a9"
  },
  "iv-ap-hottest-planets-1": {
    "columns": [
      "planet_name",
      "equilibrium_temp_k"
    ],
    "rowCount": 5,
    "orderedRowHash": "28799e5a631820614ac2fa14dd634bdf8994013d0f95b8b7ea579143dac8768c",
    "unorderedRowHash": "201a6fc29b52a058c311e41a75526723d98c30d1d0de9e032762f7ad8a25f648"
  },
  "iv-ap-largest-planets-1": {
    "columns": [
      "planet_name",
      "planet_type",
      "radius_earth"
    ],
    "rowCount": 10,
    "orderedRowHash": "4e78156c56044bb0a461dcf06b5aaf39b4c478a8313ea9a2338f2a83618fad98",
    "unorderedRowHash": "45a9c3069ab0029c7293848b60fe629de27ad796a3f267af581ada953f3900b7"
  },
  "iv-ap-m-dwarf-planets-1": {
    "columns": [
      "planet_name",
      "star_name"
    ],
    "rowCount": 49,
    "orderedRowHash": "cb691bd3c1c0b20c44ba0d3cfb26d7d33c9ac01fff09ff970d953670b5c570d2",
    "unorderedRowHash": "cb691bd3c1c0b20c44ba0d3cfb26d7d33c9ac01fff09ff970d953670b5c570d2"
  },
  "iv-sl-kr-roster-1": {
    "columns": [
      "handle",
      "role",
      "team_name",
      "elo_rating"
    ],
    "rowCount": 38,
    "orderedRowHash": "ecc948dd275b830da8bebbc7e128d273b77887c7c3645938c05b8467c3444eae",
    "unorderedRowHash": "a4c99108de70a771b6429338b6d36446576202c77173a6a381455079a4946511"
  },
  "iv-sl-sponsor-value-1": {
    "columns": [
      "team_name",
      "total_annual_value"
    ],
    "rowCount": 40,
    "orderedRowHash": "d59ab045bf008c063185ec3662f9c69df7224ba1bcb08e13b95cd24f184db197",
    "unorderedRowHash": "b92f3d0f48162cfcfef40da75ca0040344bae0fb4885c9a0588eb29f19994d78"
  },
  "iv-sl-no-sponsor-1": {
    "columns": [
      "team_name",
      "region_code",
      "elo_rating"
    ],
    "rowCount": 7,
    "orderedRowHash": "f5db2b894700b1ae033fdf5032e89a9f72e44e06e722ad705f4316ff1c6fd878",
    "unorderedRowHash": "bc60d099e2a0b76bf13632ef396953aa3c884d1d40463d156a90cec983c02f09"
  },
  "iv-sl-elite-sponsors-1": {
    "columns": [
      "sponsor_name",
      "industry",
      "headquarters_country"
    ],
    "rowCount": 8,
    "orderedRowHash": "5bee0806d67813766302b3db331cc38afa931c7ce94c34b4d3095b45d30d3609",
    "unorderedRowHash": "5bee0806d67813766302b3db331cc38afa931c7ce94c34b4d3095b45d30d3609"
  },
  "iv-sl-teammate-pairs-1": {
    "columns": [
      "team_name",
      "player_a",
      "player_b"
    ],
    "rowCount": 41,
    "orderedRowHash": "1cf4ec465938d504e43ba981342ffa6c4c5caf678c9109441c9401764ede3bba",
    "unorderedRowHash": "1cf4ec465938d504e43ba981342ffa6c4c5caf678c9109441c9401764ede3bba"
  },
  "iv-sl-above-team-avg-1": {
    "columns": [
      "handle",
      "team_name",
      "total_earnings_usd",
      "team_avg"
    ],
    "rowCount": 115,
    "orderedRowHash": "3454628717730cbe2c454c16bbeb6ad5f1d01496568256c689dcf8be13cae87c",
    "unorderedRowHash": "ff1a1b965da17f6feb9ded313f59911bedc69d504c4ea52dfe0aebe662685161"
  },
  "iv-sl-win-rate-1": {
    "columns": [
      "team_name",
      "matches_played",
      "matches_won",
      "win_pct"
    ],
    "rowCount": 39,
    "orderedRowHash": "e5697caa560fef6e08572664375d9a2886f22776db4624d6875a31a6d7c120a8",
    "unorderedRowHash": "37f83e9250c9a8ee15a617ebc56b0fe203e506fdabdf8498f174a4c511fde483"
  },
  "iv-sl-region-top-earner-1": {
    "columns": [
      "region_code",
      "handle",
      "total_earnings_usd"
    ],
    "rowCount": 8,
    "orderedRowHash": "26f8266b1508ab3b55fceb60eac48e0f5c5857936801bbc3110b0325264765ee",
    "unorderedRowHash": "26f8266b1508ab3b55fceb60eac48e0f5c5857936801bbc3110b0325264765ee"
  },
  "iv-sl-elo-rank-1": {
    "columns": [
      "region_code",
      "team_name",
      "elo_rating",
      "elo_rank"
    ],
    "rowCount": 40,
    "orderedRowHash": "8dec3ac406d4362880062bfc6f367f7b283fc1e41f204f021d0a7a76984e3d0c",
    "unorderedRowHash": "7fe7543b71f5d894d31eb3439410e9ada81ff8ae8f7502fb6d5c6c11cd0de0eb"
  },
  "iv-sl-prize-delta-1": {
    "columns": [
      "tournament_name",
      "start_date",
      "prize_pool_usd",
      "delta_vs_prev"
    ],
    "rowCount": 24,
    "orderedRowHash": "50c79eb8a00f5fe99ec3d311124bb25b6597c27df589417a192904e093dd88fb",
    "unorderedRowHash": "f52525a7661e075b768b7f36f213fed37f5199a1ed5dfce1f05a9142a8d77dff"
  },
  "iv-sl-match-runtotal-1": {
    "columns": [
      "month_start",
      "matches_in_month",
      "running_total_matches"
    ],
    "rowCount": 22,
    "orderedRowHash": "db586a23401f029b73a1c4f04fc2153c83161e976d88dd1eab3e35929fc23d00",
    "unorderedRowHash": "db586a23401f029b73a1c4f04fc2153c83161e976d88dd1eab3e35929fc23d00"
  },
  "iv-sl-role-top3-1": {
    "columns": [
      "role",
      "handle",
      "total_earnings_usd",
      "earnings_rank"
    ],
    "rowCount": 18,
    "orderedRowHash": "45d1fada034bd0e7d0ff233ce79ecd5062b826b2feeebcba5dc3d55cf3deea4c",
    "unorderedRowHash": "4eb6add380cd080b8d0c9f14d5ed2d8f87573f1573a0d1535b93ae37c01431ef"
  },
  "iv-rv-payment-dedup-1": {
    "columns": [
      "order_month",
      "orders",
      "dup_payment_rows_removed",
      "deduped_amount_cents"
    ],
    "rowCount": 12,
    "orderedRowHash": "431b04a7af5dc070342df2d06446ff00278110aa1f71ac7f3c485bb6ef19fc52",
    "unorderedRowHash": "431b04a7af5dc070342df2d06446ff00278110aa1f71ac7f3c485bb6ef19fc52"
  },
  "iv-rv-courier-top3-1": {
    "columns": [
      "home_city_id",
      "courier_id",
      "lifetime_deliveries",
      "rnk"
    ],
    "rowCount": 48,
    "orderedRowHash": "e6a8427fccba36c71dd967859e99945f9afe54aa81cced3fa166d3a1aaae4c15",
    "unorderedRowHash": "2469b87b6f085601674ac7b650c1da218dceadfa1cad2beb2cb4fb68940ea7e5"
  },
  "iv-rv-acquisition-funnel-1": {
    "columns": [
      "stage_rank",
      "stage",
      "customers",
      "pct_of_entry"
    ],
    "rowCount": 6,
    "orderedRowHash": "b7802b6ff545e559b478f18847b84365d78858ed8634d647c4d4d3dd5c645bfe",
    "unorderedRowHash": "b7802b6ff545e559b478f18847b84365d78858ed8634d647c4d4d3dd5c645bfe"
  },
  "iv-rv-cohort-retention-1": {
    "columns": [
      "cohort_month",
      "month_offset",
      "cohort_size",
      "retained",
      "retention_pct"
    ],
    "rowCount": 24,
    "orderedRowHash": "96f7478657f57f17c34f1c25aadd784461ba57ac96ae092175f6fec82bd9e3b5",
    "unorderedRowHash": "96f7478657f57f17c34f1c25aadd784461ba57ac96ae092175f6fec82bd9e3b5"
  },
  "iv-rv-sessionization-1": {
    "columns": [
      "session_day",
      "sessions",
      "total_events",
      "avg_events_per_session"
    ],
    "rowCount": 7,
    "orderedRowHash": "dfd5f38bef4447c0d36d0f2af6d96504725ea7239f8dd32f1ee507ebef68ccf3",
    "unorderedRowHash": "dfd5f38bef4447c0d36d0f2af6d96504725ea7239f8dd32f1ee507ebef68ccf3"
  },
  "iv-rv-orders-movingavg-1": {
    "columns": [
      "order_date",
      "daily_orders",
      "ma_7"
    ],
    "rowCount": 90,
    "orderedRowHash": "71104f9239cd00a3dbd85edcc7f1e5cc5d5026eb1081d4c6883161f74783ecde",
    "unorderedRowHash": "71104f9239cd00a3dbd85edcc7f1e5cc5d5026eb1081d4c6883161f74783ecde"
  },
  "iv-rv-money-text-clean-1": {
    "columns": [
      "order_date",
      "orders",
      "parsed_orders",
      "missing_legacy",
      "parsed_cents"
    ],
    "rowCount": 28,
    "orderedRowHash": "b2b26b371fa0f5cced5b73e1835d301244605419dea51799277c9883ed42f1ba",
    "unorderedRowHash": "b2b26b371fa0f5cced5b73e1835d301244605419dea51799277c9883ed42f1ba"
  },
  "iv-rv-tip-bucketing-1": {
    "columns": [
      "tip_bucket",
      "orders",
      "pct_of_orders"
    ],
    "rowCount": 4,
    "orderedRowHash": "2861cde764a445d9c5eb7b6b7257d2bb534cad14d983fe5876ab3c6defb0cab2",
    "unorderedRowHash": "2861cde764a445d9c5eb7b6b7257d2bb534cad14d983fe5876ab3c6defb0cab2"
  },
  "iv-rv-orphan-orders-1": {
    "columns": [
      "order_month",
      "orphaned_orders",
      "orphaned_amount_cents"
    ],
    "rowCount": 12,
    "orderedRowHash": "555a425717b4669f776edb6747cfe44d96c550953a66d62cdbfbe98a474013cb",
    "unorderedRowHash": "555a425717b4669f776edb6747cfe44d96c550953a66d62cdbfbe98a474013cb"
  },
  "iv-rv-category-tree-1": {
    "columns": [
      "category_id",
      "name",
      "depth",
      "root_name"
    ],
    "rowCount": 34,
    "orderedRowHash": "80a310bb700daa9e8962e1bfc670dadce48d8f460edaf67c7d5d803a3a378de0",
    "unorderedRowHash": "2efd1559f859c5ec5a49bccf9caf0745774bde41b0b6ef3961d336ed1244e306"
  },
  "iv-rv-customer-dedup-1": {
    "columns": [
      "acquisition_channel",
      "raw_rows",
      "deduped_customers"
    ],
    "rowCount": 5,
    "orderedRowHash": "a7530f5e0ee3ce0cd9693784bb27a90f94dc31dc2403cc3bb5373b26d84e1175",
    "unorderedRowHash": "a7530f5e0ee3ce0cd9693784bb27a90f94dc31dc2403cc3bb5373b26d84e1175"
  },
  "iv-rv-utc-hour-1": {
    "columns": [
      "utc_hour",
      "orders"
    ],
    "rowCount": 24,
    "orderedRowHash": "b720e697943f6e781d8344e788c3ae5fe89eadeeae605d08475fd0ac6bf72d5f",
    "unorderedRowHash": "55140a7501383f560286e9691fc919815b33602e7bce2287a0e840dd290eb8be"
  }
};
