-- SQL Mastery curriculum databases: create with C collation.
--
-- WHY C COLLATION IS REQUIRED (do not change to a locale collation):
-- Grading uses precomputed result fingerprints and a serve-time snapshot guard.
-- Both hash query results whose row order depends on the database collation. Locale
-- collations (glibc en_US.UTF-8 on Linux, Windows-1252 on Windows, or any ICU build)
-- sort text differently across OS and library versions, so artifacts validated on one
-- machine drift on another and the server refuses to start. C collation is pure byte
-- order: identical on every OS, glibc/ICU version, and PostgreSQL major version. This
-- makes the committed snapshots and fingerprints reproducible everywhere.
--
-- Run as a superuser from the 'postgres' maintenance database:
--   psql -U <superuser> -d postgres -f scripts/create-databases.sql
--
-- This DROPS and recreates the three curriculum databases. That is safe: only the
-- synthetic/public curriculum data lives here (regenerated by the seed scripts). App
-- user accounts are file-based (SQL_MASTERY_DATA_DIR), not in these databases.
--
-- After creating, seed (npm run / node dist/scripts/seed-all.js) and, on a server where
-- the app connects as a non-owner role (e.g. sqlrunner), grant read access, e.g.:
--   ALTER DEFAULT PRIVILEGES FOR ROLE <seeding_role> IN SCHEMA public
--     GRANT SELECT ON TABLES TO sqlrunner;   -- set BEFORE seeding so new tables inherit it
--   GRANT USAGE ON SCHEMA public TO sqlrunner;

\set ON_ERROR_STOP on

SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'aperture' AND pid <> pg_backend_pid();
DROP DATABASE IF EXISTS aperture;
CREATE DATABASE aperture TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';

SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'sideline' AND pid <> pg_backend_pid();
DROP DATABASE IF EXISTS sideline;
CREATE DATABASE sideline TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';

SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'rove' AND pid <> pg_backend_pid();
DROP DATABASE IF EXISTS rove;
CREATE DATABASE rove TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
