import * as fs from 'node:fs';
import * as path from 'node:path';

import { createQueryService } from '../src/query-service';
import { buildExercisesFor } from '../src/generator/index';
import { curate } from '../src/generator/curate';
import type { ConceptMeta, DraftExercise, Exercise } from '../src/generator/types';
import { APERTURE_CONCEPT_META } from '../src/generator/templates/aperture/index';
import { SIDELINE_CONCEPT_META } from '../src/generator/templates/sideline/index';
import { ROVE_CONCEPT_META } from '../src/generator/templates/rove/index';
import { recordSnapshot } from '../src/snapshot';
import { validateExercises } from './validate-exercises';

const ALL_DBS = ['aperture', 'sideline', 'rove'] as const;
type Db = (typeof ALL_DBS)[number];

const META: Record<Db, ConceptMeta[]> = {
  aperture: APERTURE_CONCEPT_META,
  sideline: SIDELINE_CONCEPT_META,
  rove: ROVE_CONCEPT_META
};

export function parseDbArg(argv: string[]): string[] {
  const index = argv.indexOf('--db');
  if (index >= 0) {
    const db = argv[index + 1];
    if (!ALL_DBS.includes(db as Db)) {
      throw new Error(`unknown --db "${db}"; expected one of ${ALL_DBS.join(', ')}`);
    }
    return [db];
  }
  return [...ALL_DBS];
}

export function generatedFilePath(database: string): string {
  return path.join(__dirname, '..', '..', 'src', 'phases', database, 'exercises.generated.ts');
}

export function serializeGeneratedFile(bySkill: Record<string, Exercise[]>): string {
  const ordered: Record<string, Exercise[]> = {};
  for (const skill of Object.keys(bySkill).sort()) {
    ordered[skill] = bySkill[skill];
  }
  return [
    '// AUTO-GENERATED by scripts/generate-exercises.ts. DO NOT EDIT BY HAND.',
    '// Regenerate with: npm run generate-exercises',
    "import type { Exercise } from '../../generator/types';",
    '',
    `export const GENERATED_EXERCISES: Record<string, Exercise[]> = ${JSON.stringify(ordered, null, 2)};`,
    ''
  ].join('\n');
}

async function main(): Promise<void> {
  const dbs = parseDbArg(process.argv.slice(2));
  const service = createQueryService();
  let anyFailure = false;

  try {
    for (const db of dbs) {
      const drafts: DraftExercise[] = await buildExercisesFor(db);
      const curated = curate(drafts, META[db as Db]);
      const exercises = curated as unknown as Exercise[];

      if (exercises.length === 0) {
        const file = generatedFilePath(db);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, serializeGeneratedFile({}));
        console.log(`generate-exercises: wrote 0 exercises across 0 skills -> ${file}`);
        continue;
      }

      const { passed, failures } = await validateExercises(exercises, { service: service as any });
      if (failures.length) {
        anyFailure = true;
        console.error(`generate-exercises: ${db} FAILED validation (${failures.length}); not writing`);
        for (const failure of failures) {
          const reasons = failure.results.filter((result) => !result.pass).map((result) => `${result.gate}:${result.message}`).join('; ');
          console.error(`  FAIL ${failure.id} -> ${reasons}`);
        }
        continue;
      }

      const bySkill: Record<string, Exercise[]> = {};
      for (const exercise of passed) {
        if (!bySkill[exercise.skill]) bySkill[exercise.skill] = [];
        bySkill[exercise.skill].push(exercise);
      }

      const file = generatedFilePath(db);
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, serializeGeneratedFile(bySkill));
      await recordSnapshot(db, { service: service as any });
      console.log(`generate-exercises: wrote ${passed.length} exercises across ${Object.keys(bySkill).length} skills -> ${file}`);
    }
  } finally {
    await service.close();
  }

  if (anyFailure) process.exit(1);
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
