// Validate hand-authored interview problems against the seeded databases and bake their
// result fingerprints. Mirrors validate-exercises: each expectedSql must run, be non-empty,
// stay under its row ceiling, and (when orderMatters) be deterministically ordered. Writes
// src/interview/fingerprints.generated.ts so only validated problems are served + gradeable.
import * as fs from 'node:fs';
import * as path from 'node:path';
import { createQueryService } from '../src/query-service';
import { buildFingerprint, type Fingerprint } from '../src/fingerprint';
import { INTERVIEW_DRAFTS } from '../src/interview';

function regexNames(column: string): RegExp {
  return new RegExp('\\b' + column.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b', 'i');
}

async function main(): Promise<void> {
  const service = createQueryService() as any;
  const fingerprints: Record<string, Fingerprint> = {};
  const failures: string[] = [];
  const warnings: string[] = [];
  let passed = 0;

  for (const problem of INTERVIEW_DRAFTS) {
    try {
      const ceiling = Math.min(problem.rowCeiling || 200, 200);
      const first = await service.executeQuery({ database: problem.database, sql: problem.expectedSql, rowMode: 'array' });
      const rows = Array.isArray(first.rows) ? first.rows : [];
      if (rows.length < 1) { failures.push(`${problem.id}: empty result`); continue; }
      if (rows.length > ceiling) { failures.push(`${problem.id}: ${rows.length} rows exceeds ceiling ${ceiling}`); continue; }

      const fingerprint = buildFingerprint({ fields: first.fields, rows: first.rows });

      if (problem.orderMatters) {
        const second = await service.executeQuery({ database: problem.database, sql: problem.expectedSql, rowMode: 'array' });
        const again = buildFingerprint({ fields: second.fields, rows: second.rows });
        if (fingerprint.orderedRowHash !== again.orderedRowHash) {
          failures.push(`${problem.id}: non-deterministic row order (add a unique ORDER BY tiebreaker)`);
          continue;
        }
      }

      const unnamed = fingerprint.columns.filter((c) => !regexNames(c).test(problem.task));
      if (unnamed.length) warnings.push(`${problem.id}: task does not name output column(s): ${unnamed.join(', ')}`);

      fingerprints[problem.id] = fingerprint;
      passed += 1;
    } catch (error: any) {
      failures.push(`${problem.id}: ${(error && error.message) || error}`);
    }
  }

  const file = path.join(__dirname, '..', '..', 'src', 'interview', 'fingerprints.generated.ts');
  const body =
    `import type { Fingerprint } from '../fingerprint';\n\n` +
    `// Generated by scripts/validate-interview.ts. Do not edit by hand.\n` +
    `// Maps an interview problem id to the result fingerprint baked from its expectedSql.\n` +
    `export const INTERVIEW_FINGERPRINTS: Record<string, Fingerprint> = ${JSON.stringify(fingerprints, null, 2)};\n`;
  fs.writeFileSync(file, body);

  if (typeof service.close === 'function') await service.close();

  console.log(`validate-interview: ${passed} passed, ${failures.length} failed, ${warnings.length} warnings`);
  for (const w of warnings) console.log('  WARN ' + w);
  for (const f of failures) console.log('  FAIL ' + f);
  if (failures.length) process.exit(1);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
