// AUTO-GENERATED by scripts/generate-exercises.ts. DO NOT EDIT BY HAND.
// Regenerate with: npm run generate-exercises
import type { Exercise } from '../../generator/types';

export const GENERATED_EXERCISES: Record<string, Exercise[]> = {
  "ap-aggregate-scalar": [
    {
      "id": "ap-aggregate-scalar-eo4hpu",
      "skill": "ap-aggregate-scalar",
      "database": "aperture",
      "task": "Return planet_count and avg_mass for all planets, ordered by planet_count. Return columns: planet_count, avg_mass. Order by: planet_count.",
      "starterSql": {
        "full": "SELECT COUNT(*) AS planet_count, ROUND(AVG(mass_earth), 2) AS avg_mass FROM planets ORDER BY planet_count",
        "half": "SELECT COUNT(*) AS planet_count, ROUND(AVG(mass_earth), 2) AS avg_mass FROM planets ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {},
        "half": {
          "__BLANK_0__": "planet_count"
        },
        "blank": {
          "__BLANK_0__": "COUNT(*) AS planet_count, ROUND(AVG(mass_earth), 2) AS avg_mass",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "planet_count"
        }
      },
      "hint": "With no GROUP BY, COUNT and AVG summarize the whole table into one row.",
      "expectedSql": "SELECT COUNT(*) AS planet_count, ROUND(AVG(mass_earth), 2) AS avg_mass FROM planets ORDER BY planet_count",
      "orderMatters": false,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_count",
          "avg_mass"
        ],
        "rowCount": 1,
        "orderedRowHash": "fa5cefa58e4200ef6221d7271d6d2606b87afce57056b7dded787e9a09268d70",
        "unorderedRowHash": "fa5cefa58e4200ef6221d7271d6d2606b87afce57056b7dded787e9a09268d70"
      }
    }
  ],
  "ap-column-alias": [
    {
      "id": "ap-column-alias-dole9j",
      "skill": "ap-column-alias",
      "database": "aperture",
      "task": "Alias star_name as name and distance_ly as light_years, with star_id, ordered by star_id. Return columns: star_id, name, light_years. Order by: star_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS star_id, star_name AS name, distance_ly AS light_years FROM stars ORDER BY __BLANK_1__",
        "half": "SELECT star_id AS star_id, star_name AS name, distance_ly AS light_years FROM stars ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "star_id",
          "__BLANK_1__": "star_id"
        },
        "half": {
          "__BLANK_0__": "star_id"
        },
        "blank": {
          "__BLANK_0__": "star_id AS star_id, star_name AS name, distance_ly AS light_years",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "star_id"
        }
      },
      "hint": "AS changes the output header for a column.",
      "expectedSql": "SELECT star_id AS star_id, star_name AS name, distance_ly AS light_years FROM stars ORDER BY star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "name",
          "light_years"
        ],
        "rowCount": 77,
        "orderedRowHash": "44a2fac2f7d24263f253107309c92bef42b90d85247998696eb4ec6f57ffdeca",
        "unorderedRowHash": "fab45a03efab771aa8e9475db903fe719fa1061ef5062fe315ddf5d3acf4d220"
      }
    }
  ],
  "ap-computed-columns": [
    {
      "id": "ap-computed-columns-1h9sxfv",
      "skill": "ap-computed-columns",
      "database": "aperture",
      "task": "Show planet_id, planet_name, and orbital_years from planets, ordered by planet_id. Return columns: planet_id, planet_name, orbital_years. Order by: planet_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_id, planet_name AS planet_name, orbital_period_days / 365.0 AS orbital_years FROM planets ORDER BY __BLANK_1__",
        "half": "SELECT planet_id AS planet_id, planet_name AS planet_name, orbital_period_days / 365.0 AS orbital_years FROM planets ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_id",
          "__BLANK_1__": "planet_id"
        },
        "half": {
          "__BLANK_0__": "planet_id"
        },
        "blank": {
          "__BLANK_0__": "planet_id AS planet_id, planet_name AS planet_name, orbital_period_days / 365.0 AS orbital_years",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "planet_id"
        }
      },
      "hint": "Put orbital_period_days / 365.0 in the SELECT list and name it with AS.",
      "expectedSql": "SELECT planet_id AS planet_id, planet_name AS planet_name, orbital_period_days / 365.0 AS orbital_years FROM planets ORDER BY planet_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "orbital_years"
        ],
        "rowCount": 140,
        "orderedRowHash": "a7ffd68c7285899caa0ef8182743ec97c3d4f2a4ca4081c467038a0c4919dec1",
        "unorderedRowHash": "2658b99b19c6747b5a9373d488f45369376bd733bb8a87c257d371c69a6ad30f"
      }
    }
  ],
  "ap-distinct": [
    {
      "id": "ap-distinct-1hbgeyg",
      "skill": "ap-distinct",
      "database": "aperture",
      "task": "List every distinct planet_name value in planets, ordered by planet_name. Return columns: planet_name. Order by: planet_name.",
      "starterSql": {
        "full": "SELECT DISTINCT __BLANK_0__ AS planet_name FROM planets ORDER BY __BLANK_1__",
        "half": "SELECT DISTINCT planet_name AS planet_name FROM planets ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_name",
          "__BLANK_1__": "planet_name"
        },
        "half": {
          "__BLANK_0__": "planet_name"
        },
        "blank": {
          "__BLANK_0__": "DISTINCT planet_name AS planet_name",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "planet_name"
        }
      },
      "hint": "SELECT DISTINCT keeps one row for each unique planet_name.",
      "expectedSql": "SELECT DISTINCT planet_name AS planet_name FROM planets ORDER BY planet_name",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_name"
        ],
        "rowCount": 140,
        "orderedRowHash": "44a4a4f9e76b29e5c9fee8e0af9ee20b51b79d68871493a0a0dcf9f5f673cba2",
        "unorderedRowHash": "d98d8e3b236d2f29d1234f13343f9e204ff365bfc44c318150e37b11c8435545"
      }
    },
    {
      "id": "ap-distinct-4m3a1l",
      "skill": "ap-distinct",
      "database": "aperture",
      "task": "Show each unique planet_type from planets once, ordered by planet_type. Return columns: planet_type. Order by: planet_type.",
      "starterSql": {
        "full": "SELECT DISTINCT __BLANK_0__ AS planet_type FROM planets ORDER BY __BLANK_1__",
        "half": "SELECT DISTINCT planet_type AS planet_type FROM planets ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_type",
          "__BLANK_1__": "planet_type"
        },
        "half": {
          "__BLANK_0__": "planet_type"
        },
        "blank": {
          "__BLANK_0__": "DISTINCT planet_type AS planet_type",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "planet_type"
        }
      },
      "hint": "SELECT DISTINCT keeps one row for each unique planet_type.",
      "expectedSql": "SELECT DISTINCT planet_type AS planet_type FROM planets ORDER BY planet_type",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_type"
        ],
        "rowCount": 4,
        "orderedRowHash": "709a4f0c065b4cdaff704bbdba77e7c2d2ee84147676fb6eadc8d9c9ec11a1fd",
        "unorderedRowHash": "709a4f0c065b4cdaff704bbdba77e7c2d2ee84147676fb6eadc8d9c9ec11a1fd"
      }
    },
    {
      "id": "ap-distinct-qwrokc",
      "skill": "ap-distinct",
      "database": "aperture",
      "task": "List every distinct discovery_method value in planets, ordered by discovery_method. Return columns: discovery_method. Order by: discovery_method.",
      "starterSql": {
        "full": "SELECT DISTINCT __BLANK_0__ AS discovery_method FROM planets ORDER BY __BLANK_1__",
        "half": "SELECT DISTINCT discovery_method AS discovery_method FROM planets ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "discovery_method",
          "__BLANK_1__": "discovery_method"
        },
        "half": {
          "__BLANK_0__": "discovery_method"
        },
        "blank": {
          "__BLANK_0__": "DISTINCT discovery_method AS discovery_method",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "discovery_method"
        }
      },
      "hint": "SELECT DISTINCT keeps one row for each unique discovery_method.",
      "expectedSql": "SELECT DISTINCT discovery_method AS discovery_method FROM planets ORDER BY discovery_method",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "discovery_method"
        ],
        "rowCount": 5,
        "orderedRowHash": "181d7815eb04aba3d1697309282f4238918768c5c2798e5dcafe0454e65ef42d",
        "unorderedRowHash": "181d7815eb04aba3d1697309282f4238918768c5c2798e5dcafe0454e65ef42d"
      }
    }
  ],
  "ap-group-by": [
    {
      "id": "ap-group-by-1df2jwu",
      "skill": "ap-group-by",
      "database": "aperture",
      "task": "Count planets into n for each discovery_year value, returning discovery_year and n ordered by discovery_year. Return columns: discovery_year, n. Order by: discovery_year.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS discovery_year, COUNT(*) AS n FROM planets GROUP BY __BLANK_1__ ORDER BY __BLANK_2__",
        "half": "SELECT discovery_year AS discovery_year, COUNT(*) AS n FROM planets GROUP BY __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ GROUP BY __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "discovery_year",
          "__BLANK_1__": "discovery_year",
          "__BLANK_2__": "discovery_year"
        },
        "half": {
          "__BLANK_0__": "discovery_year",
          "__BLANK_1__": "discovery_year"
        },
        "blank": {
          "__BLANK_0__": "discovery_year AS discovery_year, COUNT(*) AS n",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "discovery_year",
          "__BLANK_3__": "discovery_year"
        }
      },
      "hint": "GROUP BY discovery_year creates one bucket per value, then COUNT(*) counts the bucket.",
      "expectedSql": "SELECT discovery_year AS discovery_year, COUNT(*) AS n FROM planets GROUP BY discovery_year ORDER BY discovery_year",
      "orderMatters": false,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "discovery_year",
          "n"
        ],
        "rowCount": 29,
        "orderedRowHash": "66f0d134f94290a8ec3bcd4be93aae9357602f3d97459fe49614ab9e4b5ac6c3",
        "unorderedRowHash": "66f0d134f94290a8ec3bcd4be93aae9357602f3d97459fe49614ab9e4b5ac6c3"
      }
    },
    {
      "id": "ap-group-by-frzqdy",
      "skill": "ap-group-by",
      "database": "aperture",
      "task": "Return discovery_method and n by counting planets for each discovery_method, ordered by discovery_method. Return columns: discovery_method, n. Order by: discovery_method.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS discovery_method, COUNT(*) AS n FROM planets GROUP BY __BLANK_1__ ORDER BY __BLANK_2__",
        "half": "SELECT discovery_method AS discovery_method, COUNT(*) AS n FROM planets GROUP BY __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ GROUP BY __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "discovery_method",
          "__BLANK_1__": "discovery_method",
          "__BLANK_2__": "discovery_method"
        },
        "half": {
          "__BLANK_0__": "discovery_method",
          "__BLANK_1__": "discovery_method"
        },
        "blank": {
          "__BLANK_0__": "discovery_method AS discovery_method, COUNT(*) AS n",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "discovery_method",
          "__BLANK_3__": "discovery_method"
        }
      },
      "hint": "GROUP BY discovery_method creates one bucket per value, then COUNT(*) counts the bucket.",
      "expectedSql": "SELECT discovery_method AS discovery_method, COUNT(*) AS n FROM planets GROUP BY discovery_method ORDER BY discovery_method",
      "orderMatters": false,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "discovery_method",
          "n"
        ],
        "rowCount": 5,
        "orderedRowHash": "124b6aca2a9c268d466f35cfef5deb22b77af232f2bd6cd5c22869649cb98480",
        "unorderedRowHash": "124b6aca2a9c268d466f35cfef5deb22b77af232f2bd6cd5c22869649cb98480"
      }
    },
    {
      "id": "ap-group-by-lfl7r7",
      "skill": "ap-group-by",
      "database": "aperture",
      "task": "Count planets into n for each planet_type value, returning planet_type and n ordered by planet_type. Return columns: planet_type, n. Order by: planet_type.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_type, COUNT(*) AS n FROM planets GROUP BY __BLANK_1__ ORDER BY __BLANK_2__",
        "half": "SELECT planet_type AS planet_type, COUNT(*) AS n FROM planets GROUP BY __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ GROUP BY __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_type",
          "__BLANK_1__": "planet_type",
          "__BLANK_2__": "planet_type"
        },
        "half": {
          "__BLANK_0__": "planet_type",
          "__BLANK_1__": "planet_type"
        },
        "blank": {
          "__BLANK_0__": "planet_type AS planet_type, COUNT(*) AS n",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "planet_type",
          "__BLANK_3__": "planet_type"
        }
      },
      "hint": "GROUP BY planet_type creates one bucket per value, then COUNT(*) counts the bucket.",
      "expectedSql": "SELECT planet_type AS planet_type, COUNT(*) AS n FROM planets GROUP BY planet_type ORDER BY planet_type",
      "orderMatters": false,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_type",
          "n"
        ],
        "rowCount": 4,
        "orderedRowHash": "38c462bbb04354f99c55e50d1c97fe98fdf0960aa2f8a39564569a912314be5e",
        "unorderedRowHash": "38c462bbb04354f99c55e50d1c97fe98fdf0960aa2f8a39564569a912314be5e"
      }
    }
  ],
  "ap-group-by-sort-top": [
    {
      "id": "ap-group-by-sort-top-1ns26nk",
      "skill": "ap-group-by-sort-top",
      "database": "aperture",
      "task": "Show 3 discovery_method groups with n, ordered by discovery_method. Return columns: discovery_method, n. Order by: discovery_method.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS discovery_method, COUNT(*) AS n FROM planets GROUP BY __BLANK_1__ ORDER BY __BLANK_2__ LIMIT __BLANK_3__",
        "half": "SELECT discovery_method AS discovery_method, COUNT(*) AS n FROM planets GROUP BY discovery_method ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ GROUP BY __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "discovery_method",
          "__BLANK_1__": "discovery_method",
          "__BLANK_2__": "discovery_method",
          "__BLANK_3__": "3"
        },
        "half": {
          "__BLANK_0__": "discovery_method",
          "__BLANK_1__": "3"
        },
        "blank": {
          "__BLANK_0__": "discovery_method AS discovery_method, COUNT(*) AS n",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "discovery_method",
          "__BLANK_3__": "discovery_method",
          "__BLANK_4__": "3"
        }
      },
      "hint": "Group first, then keep only 3 grouped rows.",
      "expectedSql": "SELECT discovery_method AS discovery_method, COUNT(*) AS n FROM planets GROUP BY discovery_method ORDER BY discovery_method LIMIT 3",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "discovery_method",
          "n"
        ],
        "rowCount": 3,
        "orderedRowHash": "c2efa7e06b42054873b08ffa28e38c850f2baa90754018d517c9a006ab1d6faa",
        "unorderedRowHash": "c2efa7e06b42054873b08ffa28e38c850f2baa90754018d517c9a006ab1d6faa"
      }
    },
    {
      "id": "ap-group-by-sort-top-b8eqmd",
      "skill": "ap-group-by-sort-top",
      "database": "aperture",
      "task": "Return the first 3 grouped rows with planet_type and n, ordered by planet_type. Return columns: planet_type, n. Order by: planet_type.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_type, COUNT(*) AS n FROM planets GROUP BY __BLANK_1__ ORDER BY __BLANK_2__ LIMIT __BLANK_3__",
        "half": "SELECT planet_type AS planet_type, COUNT(*) AS n FROM planets GROUP BY planet_type ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ GROUP BY __BLANK_2__ ORDER BY __BLANK_3__ LIMIT __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_type",
          "__BLANK_1__": "planet_type",
          "__BLANK_2__": "planet_type",
          "__BLANK_3__": "3"
        },
        "half": {
          "__BLANK_0__": "planet_type",
          "__BLANK_1__": "3"
        },
        "blank": {
          "__BLANK_0__": "planet_type AS planet_type, COUNT(*) AS n",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "planet_type",
          "__BLANK_3__": "planet_type",
          "__BLANK_4__": "3"
        }
      },
      "hint": "Group first, then keep only 3 grouped rows.",
      "expectedSql": "SELECT planet_type AS planet_type, COUNT(*) AS n FROM planets GROUP BY planet_type ORDER BY planet_type LIMIT 3",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_type",
          "n"
        ],
        "rowCount": 3,
        "orderedRowHash": "51171e86bda4181c0dca42963afdae8438ed3d9b57edcd5d8f81117bb347fcd3",
        "unorderedRowHash": "51171e86bda4181c0dca42963afdae8438ed3d9b57edcd5d8f81117bb347fcd3"
      }
    }
  ],
  "ap-having": [
    {
      "id": "ap-having-11np061",
      "skill": "ap-having",
      "database": "aperture",
      "task": "Group planets by planet_type, keep groups with COUNT(*) >= 1, and return planet_type and n ordered by planet_type. Return columns: planet_type, n. Order by: planet_type.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_type, COUNT(*) AS n FROM planets GROUP BY __BLANK_1__ HAVING COUNT(*) >= 1 ORDER BY __BLANK_2__",
        "half": "SELECT planet_type AS planet_type, COUNT(*) AS n FROM planets GROUP BY planet_type HAVING __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ GROUP BY __BLANK_2__ HAVING __BLANK_3__ ORDER BY __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_type",
          "__BLANK_1__": "planet_type",
          "__BLANK_2__": "planet_type"
        },
        "half": {
          "__BLANK_0__": "COUNT(*) >= 1",
          "__BLANK_1__": "planet_type"
        },
        "blank": {
          "__BLANK_0__": "planet_type AS planet_type, COUNT(*) AS n",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "planet_type",
          "__BLANK_3__": "COUNT(*) >= 1",
          "__BLANK_4__": "planet_type"
        }
      },
      "hint": "HAVING filters aggregate groups after GROUP BY.",
      "expectedSql": "SELECT planet_type AS planet_type, COUNT(*) AS n FROM planets GROUP BY planet_type HAVING COUNT(*) >= 1 ORDER BY planet_type",
      "orderMatters": false,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_type",
          "n"
        ],
        "rowCount": 4,
        "orderedRowHash": "38c462bbb04354f99c55e50d1c97fe98fdf0960aa2f8a39564569a912314be5e",
        "unorderedRowHash": "38c462bbb04354f99c55e50d1c97fe98fdf0960aa2f8a39564569a912314be5e"
      }
    },
    {
      "id": "ap-having-k6g4v0",
      "skill": "ap-having",
      "database": "aperture",
      "task": "Return discovery_method and n for groups with COUNT(*) at least 1, ordered by discovery_method. Return columns: discovery_method, n. Order by: discovery_method.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS discovery_method, COUNT(*) AS n FROM planets GROUP BY __BLANK_1__ HAVING COUNT(*) >= 1 ORDER BY __BLANK_2__",
        "half": "SELECT discovery_method AS discovery_method, COUNT(*) AS n FROM planets GROUP BY discovery_method HAVING __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ GROUP BY __BLANK_2__ HAVING __BLANK_3__ ORDER BY __BLANK_4__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "discovery_method",
          "__BLANK_1__": "discovery_method",
          "__BLANK_2__": "discovery_method"
        },
        "half": {
          "__BLANK_0__": "COUNT(*) >= 1",
          "__BLANK_1__": "discovery_method"
        },
        "blank": {
          "__BLANK_0__": "discovery_method AS discovery_method, COUNT(*) AS n",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "discovery_method",
          "__BLANK_3__": "COUNT(*) >= 1",
          "__BLANK_4__": "discovery_method"
        }
      },
      "hint": "HAVING filters aggregate groups after GROUP BY.",
      "expectedSql": "SELECT discovery_method AS discovery_method, COUNT(*) AS n FROM planets GROUP BY discovery_method HAVING COUNT(*) >= 1 ORDER BY discovery_method",
      "orderMatters": false,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "discovery_method",
          "n"
        ],
        "rowCount": 5,
        "orderedRowHash": "124b6aca2a9c268d466f35cfef5deb22b77af232f2bd6cd5c22869649cb98480",
        "unorderedRowHash": "124b6aca2a9c268d466f35cfef5deb22b77af232f2bd6cd5c22869649cb98480"
      }
    }
  ],
  "ap-join-intro": [
    {
      "id": "ap-join-intro-166k04k",
      "skill": "ap-join-intro",
      "database": "aperture",
      "task": "Return planet_id, planet_name, and star_name for joined rows matching the habitable-zone condition, ordered by planet_id. Return columns: planet_id, planet_name, star_name. Order by: planet_id.",
      "starterSql": {
        "full": "SELECT planets.planet_id AS planet_id, planets.planet_name AS planet_name, stars.star_name AS star_name FROM planets JOIN stars ON planets.star_id = stars.star_id WHERE planets.in_habitable_zone = __BLANK_0__ ORDER BY __BLANK_1__",
        "half": "SELECT planets.planet_id AS planet_id, planets.planet_name AS planet_name, stars.star_name AS star_name FROM planets JOIN stars ON planets.star_id = stars.star_id WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "true",
          "__BLANK_1__": "planet_id"
        },
        "half": {
          "__BLANK_0__": "planets.in_habitable_zone = true",
          "__BLANK_1__": "planet_id"
        },
        "blank": {
          "__BLANK_0__": "planets.planet_id AS planet_id, planets.planet_name AS planet_name, stars.star_name AS star_name",
          "__BLANK_1__": "planets JOIN stars ON planets.star_id = stars.star_id",
          "__BLANK_2__": "planets.in_habitable_zone = true",
          "__BLANK_3__": "planet_id"
        }
      },
      "hint": "Join on planets.star_id = stars.star_id to attach each planet to its host star.",
      "expectedSql": "SELECT planets.planet_id AS planet_id, planets.planet_name AS planet_name, stars.star_name AS star_name FROM planets JOIN stars ON planets.star_id = stars.star_id WHERE planets.in_habitable_zone = true ORDER BY planet_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "star_name"
        ],
        "rowCount": 28,
        "orderedRowHash": "4e1379af31818933421535ea2a53b19aa5201985c17c991f3da36b667c806705",
        "unorderedRowHash": "2177b8a24f610856836d812cc741f7c05f5011aaa7c5040cd1e7087b5364b961"
      }
    },
    {
      "id": "ap-join-intro-v6joon",
      "skill": "ap-join-intro",
      "database": "aperture",
      "task": "Join planets to stars and list planet_id, planet_name, and star_name where in_habitable_zone is false, ordered by planet_id. Return columns: planet_id, planet_name, star_name. Order by: planet_id.",
      "starterSql": {
        "full": "SELECT planets.planet_id AS planet_id, planets.planet_name AS planet_name, stars.star_name AS star_name FROM planets JOIN stars ON planets.star_id = stars.star_id WHERE planets.in_habitable_zone = __BLANK_0__ ORDER BY __BLANK_1__",
        "half": "SELECT planets.planet_id AS planet_id, planets.planet_name AS planet_name, stars.star_name AS star_name FROM planets JOIN stars ON planets.star_id = stars.star_id WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "false",
          "__BLANK_1__": "planet_id"
        },
        "half": {
          "__BLANK_0__": "planets.in_habitable_zone = false",
          "__BLANK_1__": "planet_id"
        },
        "blank": {
          "__BLANK_0__": "planets.planet_id AS planet_id, planets.planet_name AS planet_name, stars.star_name AS star_name",
          "__BLANK_1__": "planets JOIN stars ON planets.star_id = stars.star_id",
          "__BLANK_2__": "planets.in_habitable_zone = false",
          "__BLANK_3__": "planet_id"
        }
      },
      "hint": "Join on planets.star_id = stars.star_id to attach each planet to its host star.",
      "expectedSql": "SELECT planets.planet_id AS planet_id, planets.planet_name AS planet_name, stars.star_name AS star_name FROM planets JOIN stars ON planets.star_id = stars.star_id WHERE planets.in_habitable_zone = false ORDER BY planet_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "star_name"
        ],
        "rowCount": 112,
        "orderedRowHash": "5fb32abfae135ecdad907f40e573af9f189550241970ad60d7dfa1784455b825",
        "unorderedRowHash": "6294f108a705fd8449561ad960a4e44c062e79ad93cea9feb72cc2b107203760"
      }
    }
  ],
  "ap-limit-topn": [
    {
      "id": "ap-limit-topn-bc9a0z",
      "skill": "ap-limit-topn",
      "database": "aperture",
      "task": "Return 3 rows with planet_id, planet_name, and mass_earth from planets, ordered by mass_earth and planet_id. Return columns: planet_id, planet_name, mass_earth. Order by: mass_earth, planet_id.",
      "starterSql": {
        "full": "SELECT planet_id AS planet_id, planet_name AS planet_name, __BLANK_0__ AS mass_earth FROM planets ORDER BY __BLANK_1__, planet_id LIMIT __BLANK_2__",
        "half": "SELECT planet_id AS planet_id, planet_name AS planet_name, mass_earth AS mass_earth FROM planets ORDER BY __BLANK_0__ LIMIT __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__ LIMIT __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "mass_earth",
          "__BLANK_1__": "mass_earth",
          "__BLANK_2__": "3"
        },
        "half": {
          "__BLANK_0__": "mass_earth, planet_id",
          "__BLANK_1__": "3"
        },
        "blank": {
          "__BLANK_0__": "planet_id AS planet_id, planet_name AS planet_name, mass_earth AS mass_earth",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "mass_earth, planet_id",
          "__BLANK_3__": "3"
        }
      },
      "hint": "LIMIT 3 keeps only the first 3 rows of the ordered result.",
      "expectedSql": "SELECT planet_id AS planet_id, planet_name AS planet_name, mass_earth AS mass_earth FROM planets ORDER BY mass_earth, planet_id LIMIT 3",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "mass_earth"
        ],
        "rowCount": 3,
        "orderedRowHash": "7367afa304815250699b5ba4440f17b3c7760a8d12509c1a66101fe541c24ce5",
        "unorderedRowHash": "d5f74b18e9ff9b71a4717cc6a192ad5527eb007861222b7c52b183a20a520c8a"
      }
    }
  ],
  "ap-null-handling": [
    {
      "id": "ap-null-handling-1ykv15p",
      "skill": "ap-null-handling",
      "database": "aperture",
      "task": "Return planet_id, planet_name, and equilibrium_temp_k for rows with missing equilibrium_temp_k, ordered by planet_id. Return columns: planet_id, planet_name, equilibrium_temp_k. Order by: planet_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_id, planet_name AS planet_name, equilibrium_temp_k AS equilibrium_temp_k FROM planets WHERE equilibrium_temp_k IS NULL ORDER BY __BLANK_1__",
        "half": "SELECT planet_id AS planet_id, planet_name AS planet_name, equilibrium_temp_k AS equilibrium_temp_k FROM planets WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_id",
          "__BLANK_1__": "planet_id"
        },
        "half": {
          "__BLANK_0__": "equilibrium_temp_k IS NULL",
          "__BLANK_1__": "planet_id"
        },
        "blank": {
          "__BLANK_0__": "planet_id AS planet_id, planet_name AS planet_name, equilibrium_temp_k AS equilibrium_temp_k",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "equilibrium_temp_k IS NULL",
          "__BLANK_3__": "planet_id"
        }
      },
      "hint": "Use IS NULL to find missing values.",
      "expectedSql": "SELECT planet_id AS planet_id, planet_name AS planet_name, equilibrium_temp_k AS equilibrium_temp_k FROM planets WHERE equilibrium_temp_k IS NULL ORDER BY planet_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "equilibrium_temp_k"
        ],
        "rowCount": 9,
        "orderedRowHash": "a579f19fa463d9c4435f74f60a677bc0adc5a6b0618ec5a29dbf2f700b72c780",
        "unorderedRowHash": "bf4525c58c77f7599a6ef212db2f3d3c1e3cfdc34d592294ccce9f60738f9f1e"
      }
    }
  ],
  "ap-order-by": [
    {
      "id": "ap-order-by-1pq5s5w",
      "skill": "ap-order-by",
      "database": "aperture",
      "task": "Return star_id, star_name, and temperature_k from stars in radius_solar order, tied by star_id. Return columns: star_id, star_name, temperature_k. Order by: radius_solar, star_id.",
      "starterSql": {
        "full": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_0__, star_id",
        "half": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "radius_solar"
        },
        "half": {
          "__BLANK_0__": "radius_solar, star_id"
        },
        "blank": {
          "__BLANK_0__": "star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "radius_solar, star_id"
        }
      },
      "hint": "The template projects star_name and temperature_k; the emitted query adds the deterministic sort.",
      "expectedSql": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY radius_solar, star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "star_name",
          "temperature_k"
        ],
        "rowCount": 77,
        "orderedRowHash": "e8d44fdec0b70407796f3033c961367297c7f131f18c0883a71a334d656fad1c",
        "unorderedRowHash": "ab04023a5cfc58e302f89f95885764e71e1232fffea512ac9920a5719d06b706"
      }
    },
    {
      "id": "ap-order-by-1r9ftqu",
      "skill": "ap-order-by",
      "database": "aperture",
      "task": "List star_id, star_name, and temperature_k, ordered by star_id and then star_id. Return columns: star_id, star_name, temperature_k. Order by: star_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_1__",
        "half": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "star_id",
          "__BLANK_1__": "star_id"
        },
        "half": {
          "__BLANK_0__": "star_id"
        },
        "blank": {
          "__BLANK_0__": "star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "star_id"
        }
      },
      "hint": "The template projects star_name and temperature_k; the emitted query adds the deterministic sort.",
      "expectedSql": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "star_name",
          "temperature_k"
        ],
        "rowCount": 77,
        "orderedRowHash": "4ba8485a188275d40fc319928bc385cf485c479b99e87b480c01ff8e8b4ce151",
        "unorderedRowHash": "ab04023a5cfc58e302f89f95885764e71e1232fffea512ac9920a5719d06b706"
      }
    },
    {
      "id": "ap-order-by-1tinoqy",
      "skill": "ap-order-by",
      "database": "aperture",
      "task": "Return star_id, star_name, and temperature_k from stars in temperature_k order, tied by star_id. Return columns: star_id, star_name, temperature_k. Order by: temperature_k, star_id.",
      "starterSql": {
        "full": "SELECT star_id AS star_id, star_name AS star_name, __BLANK_0__ AS temperature_k FROM stars ORDER BY __BLANK_1__, star_id",
        "half": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "temperature_k",
          "__BLANK_1__": "temperature_k"
        },
        "half": {
          "__BLANK_0__": "temperature_k, star_id"
        },
        "blank": {
          "__BLANK_0__": "star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "temperature_k, star_id"
        }
      },
      "hint": "The template projects star_name and temperature_k; the emitted query adds the deterministic sort.",
      "expectedSql": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY temperature_k, star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "star_name",
          "temperature_k"
        ],
        "rowCount": 77,
        "orderedRowHash": "8444e260a68cd647dc3b96029590937584b4f19654c90e3c2a1e307f83291af3",
        "unorderedRowHash": "ab04023a5cfc58e302f89f95885764e71e1232fffea512ac9920a5719d06b706"
      }
    },
    {
      "id": "ap-order-by-khjduv",
      "skill": "ap-order-by",
      "database": "aperture",
      "task": "List star_id, star_name, and temperature_k, ordered by distance_ly and then star_id. Return columns: star_id, star_name, temperature_k. Order by: distance_ly, star_id.",
      "starterSql": {
        "full": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_0__, star_id",
        "half": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "distance_ly"
        },
        "half": {
          "__BLANK_0__": "distance_ly, star_id"
        },
        "blank": {
          "__BLANK_0__": "star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "distance_ly, star_id"
        }
      },
      "hint": "The template projects star_name and temperature_k; the emitted query adds the deterministic sort.",
      "expectedSql": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY distance_ly, star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "star_name",
          "temperature_k"
        ],
        "rowCount": 77,
        "orderedRowHash": "13ff50fd61267dc7a2ff940b0e054d3d64f941bb7b6521b8a50460e40158995a",
        "unorderedRowHash": "ab04023a5cfc58e302f89f95885764e71e1232fffea512ac9920a5719d06b706"
      }
    },
    {
      "id": "ap-order-by-qw6xwa",
      "skill": "ap-order-by",
      "database": "aperture",
      "task": "List star_id, star_name, and temperature_k, ordered by mass_solar and then star_id. Return columns: star_id, star_name, temperature_k. Order by: mass_solar, star_id.",
      "starterSql": {
        "full": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_0__, star_id",
        "half": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "mass_solar"
        },
        "half": {
          "__BLANK_0__": "mass_solar, star_id"
        },
        "blank": {
          "__BLANK_0__": "star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "mass_solar, star_id"
        }
      },
      "hint": "The template projects star_name and temperature_k; the emitted query adds the deterministic sort.",
      "expectedSql": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars ORDER BY mass_solar, star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "star_name",
          "temperature_k"
        ],
        "rowCount": 77,
        "orderedRowHash": "607fdd5af1e06224076f2c105557b41ae35378cdfdf38e845d058ee1a88cc9e2",
        "unorderedRowHash": "ab04023a5cfc58e302f89f95885764e71e1232fffea512ac9920a5719d06b706"
      }
    }
  ],
  "ap-select-all": [
    {
      "id": "ap-select-all-1v8i1wq",
      "skill": "ap-select-all",
      "database": "aperture",
      "task": "Show every stars column (star_id, star_name, spectral_type, temperature_k, mass_solar, radius_solar, distance_ly), ordered by star_id. Order by: star_id.",
      "starterSql": {
        "full": "SELECT * FROM stars ORDER BY __BLANK_0__",
        "half": "SELECT * FROM stars ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "star_id"
        },
        "half": {
          "__BLANK_0__": "star_id"
        },
        "blank": {
          "__BLANK_0__": "*",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "star_id"
        }
      },
      "hint": "Use SELECT * when you want every column.",
      "expectedSql": "SELECT * FROM stars ORDER BY star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "star_name",
          "spectral_type",
          "temperature_k",
          "mass_solar",
          "radius_solar",
          "distance_ly"
        ],
        "rowCount": 77,
        "orderedRowHash": "75986a0c0480c363085c3e66127eb2eaf17e388e24dbea28d975f528487c7128",
        "unorderedRowHash": "e760c7db7f432dd368cf8c20086a92c50b7e75dea4c78afdfbfc9f7a812694ff"
      }
    }
  ],
  "ap-select-columns": [
    {
      "id": "ap-select-columns-ko3ozc",
      "skill": "ap-select-columns",
      "database": "aperture",
      "task": "Show planet_id, planet_name, and planet_type from planets, ordered by planet_id. Return columns: planet_id, planet_name, planet_type. Order by: planet_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_id, planet_name AS planet_name, planet_type AS planet_type FROM planets ORDER BY __BLANK_1__",
        "half": "SELECT planet_id AS planet_id, planet_name AS planet_name, planet_type AS planet_type FROM planets ORDER BY __BLANK_0__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ ORDER BY __BLANK_2__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_id",
          "__BLANK_1__": "planet_id"
        },
        "half": {
          "__BLANK_0__": "planet_id"
        },
        "blank": {
          "__BLANK_0__": "planet_id AS planet_id, planet_name AS planet_name, planet_type AS planet_type",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "planet_id"
        }
      },
      "hint": "Put the exact columns you need after SELECT, separated by commas.",
      "expectedSql": "SELECT planet_id AS planet_id, planet_name AS planet_name, planet_type AS planet_type FROM planets ORDER BY planet_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "planet_type"
        ],
        "rowCount": 140,
        "orderedRowHash": "3dcd60e95d1bb2c32e35d9975a1311e53fce130c1ed9df8b87729211aa320087",
        "unorderedRowHash": "f688b9fd4df2293a2c6938f6825d60dc96dbb2e495283e54a4fa9e01c914f92f"
      }
    }
  ],
  "ap-where-between-in": [
    {
      "id": "ap-where-between-in-14nz2f8",
      "skill": "ap-where-between-in",
      "database": "aperture",
      "task": "List planet_id, planet_name, and discovery_year where discovery_year is IN (2006), ordered by planet_id. Return columns: planet_id, planet_name, discovery_year. Order by: planet_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_id, planet_name AS planet_name, discovery_year AS discovery_year FROM planets WHERE discovery_year IN (__BLANK_1__) ORDER BY __BLANK_2__",
        "half": "SELECT planet_id AS planet_id, planet_name AS planet_name, discovery_year AS discovery_year FROM planets WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_id",
          "__BLANK_1__": "2006",
          "__BLANK_2__": "planet_id"
        },
        "half": {
          "__BLANK_0__": "discovery_year IN (2006)",
          "__BLANK_1__": "planet_id"
        },
        "blank": {
          "__BLANK_0__": "planet_id AS planet_id, planet_name AS planet_name, discovery_year AS discovery_year",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "discovery_year IN (2006)",
          "__BLANK_3__": "planet_id"
        }
      },
      "hint": "IN checks whether discovery_year appears inside the parenthesized list.",
      "expectedSql": "SELECT planet_id AS planet_id, planet_name AS planet_name, discovery_year AS discovery_year FROM planets WHERE discovery_year IN (2006) ORDER BY planet_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "discovery_year"
        ],
        "rowCount": 4,
        "orderedRowHash": "9ada3cab441a3b407d1d8846e85eba00aebbb8400179d5cd2b2d6f0103d64df7",
        "unorderedRowHash": "9ada3cab441a3b407d1d8846e85eba00aebbb8400179d5cd2b2d6f0103d64df7"
      }
    }
  ],
  "ap-where-boolean-logic": [
    {
      "id": "ap-where-boolean-logic-16xm5do",
      "skill": "ap-where-boolean-logic",
      "database": "aperture",
      "task": "List planet_id, planet_name, in_habitable_zone, and planet_type where in_habitable_zone is true and planet_type is Neptune-like, ordered by planet_id. Return columns: planet_id, planet_name, in_habitable_zone, planet_type. Order by: planet_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_id, planet_name AS planet_name, in_habitable_zone AS in_habitable_zone, planet_type AS planet_type FROM planets WHERE in_habitable_zone = __BLANK_1__ AND planet_type = 'Neptune-like' ORDER BY __BLANK_2__",
        "half": "SELECT planet_id AS planet_id, planet_name AS planet_name, in_habitable_zone AS in_habitable_zone, planet_type AS planet_type FROM planets WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_id",
          "__BLANK_1__": "true",
          "__BLANK_2__": "planet_id"
        },
        "half": {
          "__BLANK_0__": "in_habitable_zone = true AND planet_type = 'Neptune-like'",
          "__BLANK_1__": "planet_id"
        },
        "blank": {
          "__BLANK_0__": "planet_id AS planet_id, planet_name AS planet_name, in_habitable_zone AS in_habitable_zone, planet_type AS planet_type",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "in_habitable_zone = true AND planet_type = 'Neptune-like'",
          "__BLANK_3__": "planet_id"
        }
      },
      "hint": "AND means both WHERE conditions must be true for the same row.",
      "expectedSql": "SELECT planet_id AS planet_id, planet_name AS planet_name, in_habitable_zone AS in_habitable_zone, planet_type AS planet_type FROM planets WHERE in_habitable_zone = true AND planet_type = 'Neptune-like' ORDER BY planet_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "in_habitable_zone",
          "planet_type"
        ],
        "rowCount": 6,
        "orderedRowHash": "f045f3ef2b7a87bf6e217fd48204ef497e28d7a94586e04f932b000edfeb76a7",
        "unorderedRowHash": "f045f3ef2b7a87bf6e217fd48204ef497e28d7a94586e04f932b000edfeb76a7"
      }
    },
    {
      "id": "ap-where-boolean-logic-qcbu3u",
      "skill": "ap-where-boolean-logic",
      "database": "aperture",
      "task": "Return planet_id, planet_name, in_habitable_zone, and planet_type for rows matching both conditions, ordered by planet_id. Return columns: planet_id, planet_name, in_habitable_zone, planet_type. Order by: planet_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS planet_id, planet_name AS planet_name, in_habitable_zone AS in_habitable_zone, planet_type AS planet_type FROM planets WHERE in_habitable_zone = __BLANK_1__ AND planet_type = 'Gas Giant' ORDER BY __BLANK_2__",
        "half": "SELECT planet_id AS planet_id, planet_name AS planet_name, in_habitable_zone AS in_habitable_zone, planet_type AS planet_type FROM planets WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "planet_id",
          "__BLANK_1__": "false",
          "__BLANK_2__": "planet_id"
        },
        "half": {
          "__BLANK_0__": "in_habitable_zone = false AND planet_type = 'Gas Giant'",
          "__BLANK_1__": "planet_id"
        },
        "blank": {
          "__BLANK_0__": "planet_id AS planet_id, planet_name AS planet_name, in_habitable_zone AS in_habitable_zone, planet_type AS planet_type",
          "__BLANK_1__": "planets",
          "__BLANK_2__": "in_habitable_zone = false AND planet_type = 'Gas Giant'",
          "__BLANK_3__": "planet_id"
        }
      },
      "hint": "AND means both WHERE conditions must be true for the same row.",
      "expectedSql": "SELECT planet_id AS planet_id, planet_name AS planet_name, in_habitable_zone AS in_habitable_zone, planet_type AS planet_type FROM planets WHERE in_habitable_zone = false AND planet_type = 'Gas Giant' ORDER BY planet_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "planet_id",
          "planet_name",
          "in_habitable_zone",
          "planet_type"
        ],
        "rowCount": 37,
        "orderedRowHash": "62f7c184a5e8122ef326770f46a747a5180b5b3d9145c9ac4cbb97602009e393",
        "unorderedRowHash": "48c20b7ed8329d309ab6d83708a7c0e5c774205cb0b986fb811c9c53992d81c9"
      }
    }
  ],
  "ap-where-comparison": [
    {
      "id": "ap-where-comparison-14x8sec",
      "skill": "ap-where-comparison",
      "database": "aperture",
      "task": "Return star_id, star_name, and temperature_k for stars matching temperature_k = 6091, ordered by star_id. Return columns: star_id, star_name, temperature_k. Order by: star_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars WHERE temperature_k = __BLANK_1__ ORDER BY __BLANK_2__",
        "half": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "star_id",
          "__BLANK_1__": "6091",
          "__BLANK_2__": "star_id"
        },
        "half": {
          "__BLANK_0__": "temperature_k = 6091",
          "__BLANK_1__": "star_id"
        },
        "blank": {
          "__BLANK_0__": "star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "temperature_k = 6091",
          "__BLANK_3__": "star_id"
        }
      },
      "hint": "Put the comparison in WHERE: temperature_k = 6091.",
      "expectedSql": "SELECT star_id AS star_id, star_name AS star_name, temperature_k AS temperature_k FROM stars WHERE temperature_k = 6091 ORDER BY star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "star_name",
          "temperature_k"
        ],
        "rowCount": 1,
        "orderedRowHash": "4f7581280e360156b35ec63f266c3fab3e89a5b0c5e2979a82649269c329b230",
        "unorderedRowHash": "4f7581280e360156b35ec63f266c3fab3e89a5b0c5e2979a82649269c329b230"
      }
    }
  ],
  "ap-where-like": [
    {
      "id": "ap-where-like-1l8a7zj",
      "skill": "ap-where-like",
      "database": "aperture",
      "task": "Return star_id and star_name for stars whose star_name matches Pollux%, ordered by star_id. Return columns: star_id, star_name. Order by: star_id.",
      "starterSql": {
        "full": "SELECT __BLANK_0__ AS star_id, star_name AS star_name FROM stars WHERE star_name LIKE 'Pollux%' ORDER BY __BLANK_1__",
        "half": "SELECT star_id AS star_id, star_name AS star_name FROM stars WHERE __BLANK_0__ ORDER BY __BLANK_1__",
        "blank": "SELECT __BLANK_0__ FROM __BLANK_1__ WHERE __BLANK_2__ ORDER BY __BLANK_3__"
      },
      "blankMap": {
        "full": {
          "__BLANK_0__": "star_id",
          "__BLANK_1__": "star_id"
        },
        "half": {
          "__BLANK_0__": "star_name LIKE 'Pollux%'",
          "__BLANK_1__": "star_id"
        },
        "blank": {
          "__BLANK_0__": "star_id AS star_id, star_name AS star_name",
          "__BLANK_1__": "stars",
          "__BLANK_2__": "star_name LIKE 'Pollux%'",
          "__BLANK_3__": "star_id"
        }
      },
      "hint": "LIKE compares star_name against the text pattern Pollux%.",
      "expectedSql": "SELECT star_id AS star_id, star_name AS star_name FROM stars WHERE star_name LIKE 'Pollux%' ORDER BY star_id",
      "orderMatters": true,
      "rowCeiling": 200,
      "fingerprint": {
        "columns": [
          "star_id",
          "star_name"
        ],
        "rowCount": 1,
        "orderedRowHash": "bcd42da8326c4d6249097fbf1036a5b278467c55c0723adf6af1e9bf29fdf4a2",
        "unorderedRowHash": "bcd42da8326c4d6249097fbf1036a5b278467c55c0723adf6af1e9bf29fdf4a2"
      }
    }
  ]
};
